from flask_restx import fields, Model
from api_instance import api

add_vehicle_model = api.model('AddVehicle', {
    'vehicle_number': fields.String(required=True, description="License plate number of the vehicle"),
    'user_vehicle_model': fields.String(required=True, description="Model of the vehicle user has entered")
})

add_vehicle_model_result = api.model('AddVehicleResult', {
    'user_vehicle': fields.Nested(api.model('UserVehicle', {
        'user_id': fields.Integer(readonly=True),
        'vehicle_id': fields.Integer(readonly=True),
        'vehicle_number': fields.String(required=True, description="Vehicle's license plate number"),
        'user_vehicle_model': fields.String(required=True, description="Model of the vehicle user has entered")
    }))
})

all_vehicles_model = api.model('AllUserVehicles', {
    'user_vehicle_id': fields.Integer(readonly=True),
    'user_vehicle_name': fields.String(required=True, description="Model name user has assigned to the vehicle"),
    'vehicle_id': fields.Integer(readonly=True),
    'vehicle_number': fields.String(required=True, description="Vehicle's license plate number")
})

preset_details_model = api.model('PresetDetailsWithUserId', {
    'user_id': fields.Integer(readonly=True, example=1, description="First name of the user"),
    'presets': fields.Nested(api.model('PresetDetails', {   
        'preset_id': fields.Integer(readonly=True),
        'preset_name': fields.String(required=True, description="The name of the preset"),
        'passenger_count': fields.Integer(required=True, description="The number of passengers in the preset")
    }))
})

traveller_model_with_user_id = api.model('User', {
    'user_id': fields.Integer(required=True, example=1, description="Autogenerated id of the user"),
    'first_name': fields.String(required=True, example="Alice", description="First name of the user"),
    'middle_name': fields.String(example="J", description="Middle name of the user"),
    'last_name': fields.String(required=True, example="Smith", description="Last name of the user"),
    'passport_number': fields.String(required=True, example="A12345678", description="The passport number of the user")
})

traveller_model = api.model('Traveller', {
    'first_name': fields.String(required=True, description="First name of the traveller"),
    'middle_name': fields.String(description="Middle name of the traveller"),
    'last_name': fields.String(required=True, description="Last name of the traveller"),
    'passport_number': fields.String(required=True, description="Passport number of the traveller")
})

user_travellers_model = api.model('UserTravellers', {
    'creator_user_id': fields.Integer(required=True, example=1, description="The ID of the user who created the traveller records"),
    'travellers': fields.List(fields.Nested(traveller_model_with_user_id), 
                              example=[{
                                  "user_id": 1,
                                  "first_name": "Alice",
                                  "middle_name": "J",
                                  "last_name": "Smith",
                                  "passport_number": "A12345678"
                              }],
                              description="A list of travellers added by the user")
})

preset_with_users_model = api.model('PresetWithUsers', {
    'preset_id': fields.Integer(readonly=True),
    'preset_name': fields.String(required=True, description="Name of the preset"),
    'users': fields.List(fields.Nested(traveller_model_with_user_id))
})

preset_with_users_model_2 = api.model('PresetWithUsers2', {
    'preset_name': fields.String(required=True, description="Name of the preset"),
    'user_id': fields.Integer(required=True, example=1, description="Autogenerated id of the user"),
    'travellers': fields.List(fields.Nested(traveller_model), description="List of travellers to be added to the preset")
})

retrieve_all_presets_for_user_model = api.model('AllPresetForUser', {
    'user_id': fields.Integer(required=True, example=1, description="Autogenerated id of the user"),
    'presets_created': fields.List(fields.Nested(preset_with_users_model))
})

preset_response_model = api.model('PresetResponse', {
    'preset_id': fields.Integer(readonly=True),
    'preset_name': fields.String(required=True, description="Name of the preset"),
    'created_by_user_id': fields.Integer(description="ID of the user who created the preset"),
    'travellers_added': fields.List(fields.Nested(traveller_model_with_user_id), description="List of travellers added to the preset")
})

pass_response_model = api.model('PassResponseWithUserId', {
    'user_id': fields.Integer(required=True, example=1, description="Autogenerated id of the user"),
    "passes": fields.Nested(api.model('PassResponse', {
        'pass_id': fields.Integer(readonly=True),
        'pass_date': fields.String(required=True, description="Date when the pass was created (in String, NOT Datetime)"),
        'expiry_datetime': fields.String(required=True, description="Expiry date of the pass (in String, NOT Datetime)"),
        'pass_utilized': fields.Boolean(required=True, description="Whether the pass has been utilized for immigration"),
        'travellers': fields.List(fields.Nested(traveller_model_with_user_id), description="List of travellers associated with the pass")
    }))
})

create_pass_model = api.model('CreatePass', {
    'creator_user_id': fields.Integer(required=True, description="User ID of the creator of the pass"),
    'pass_date': fields.String(required=True, description="Date and time of the pass creation (format: YYYY-MM-DD HH:MM:SS)"),
    'pass_utilized': fields.Boolean(required=True, description="Whether the pass is utilized or not"),
    'traveller_passport_numbers': fields.List(fields.String, required = True, description="List of traveller passport numbers")
})

pass_response_model_2 = api.model('PassResponse2', {
    'pass_id': fields.Integer(readonly=True),
    'creator_user_id': fields.Integer(required=True, description="User ID of the creator of the pass"),
    'pass_date': fields.String(required=True, description="Date and time of the pass creation"),
    'expiry_datetime': fields.String(required=True, description="Expiry date and time of the pass"),
    'pass_utilized': fields.Boolean(required=True, description="Whether the pass has been utilized"),
    'travellers_added': fields.List(fields.Nested(traveller_model_with_user_id), description="List of travellers added to the pass")
})

pass_history_model = api.model('PassHistoryWithUserId', {
    'user_id': fields.Integer(required=True, example=1, description="Autogenerated id of the user"),
    "passes_utilized": fields.List(fields.Nested(api.model('PassHistory', {
        'pass_id': fields.Integer(readonly=True),
        'pass_date': fields.DateTime(required=True, description="Date when the pass was created"),
        'expiry_datetime': fields.DateTime(required=True, description="Expiry date and time of the pass")
    })))
})

first_name_model = api.model('FirstName', {
    'first_name': fields.String(
        required=True, 
        description="The first name of the user",
        example="John"
    )
})

middle_name_model = api.model('MiddleName', {
    'middle_name': fields.String(
        required=True, 
        description="The middle name of the user",
        example="David"
    )
})

last_name_model = api.model('LastName', {
    'last_name': fields.String(
        required=True, 
        description="The last name of the user",
        example="Doe"
    )
})

dob_model = api.model('DateOfBirth', {
    'date_of_birth': fields.String(
        required=True, 
        description="The date of birth of the user in YYYY-MM-DD format", 
        example="1990-01-01"
    )
})

nationality_model = api.model('Nationality', {
    'nationality': fields.String(
        required=True, 
        description="The nationality or passport issuing country of the user",
        example="American"
    )
})

passport_expiry_model = api.model('PassportExpiry', {
    'passport_expiry': fields.String(
        required=True, 
        description="The passport expiry date in YYYY-MM-DD format",
        example="2030-12-31"
    )
})

passport_number_model = api.model('PassportNumber', {
    'passport_number': fields.String(
        required=True, 
        description="The passport number of the user",
        example="A12345678"
    )
})

user_profile_model = api.model('UserProfile', {
    'first_name': fields.String(
        description="The first name of the user", 
        example="John"
    ),
    'middle_name': fields.String(
        description="The middle name of the user", 
        example="David"
    ),
    'last_name': fields.String(
        description="The last name of the user", 
        example="Doe"
    ),
    'date_of_birth': fields.String(
        description="The date of birth of the user in YYYY-MM-DD format", 
        example="1990-01-01"
    ),
    'nationality': fields.String(
        description="The nationality or passport issuing country of the user", 
        example="American"
    ),
    'passport_expiry': fields.String(
        description="The passport expiry date in YYYY-MM-DD format", 
        example="2030-12-31"
    ),
    'passport_number': fields.String(
        description="The passport number of the user", 
        example="A12345678"
    )
})
success_message_model = api.model('FieldUpdateSuccess', {
    'message': fields.String(
        required=True, 
        description="Field showing successful update of particular field", 
        example="The field you are trying to modify has been updated"
    )
})

delete_message_model = api.model('DeleteMessage', {
    'message': fields.String(
        required=True, 
        description="Message indicating successful deletion of particular resource", 
        example="The resource you are trying to delete has been deleted"
    )
})
error_response_model_400 = api.model('ErrorResponse400', {
    'error_code': fields.Integer(example = 400, description="Error code indicating the type of error"),
    'message': fields.String(example="Required fields missing or data already in database", description="Error message explaining the issue")
})
error_response_model_404 = api.model('ErrorResponse404', {
    'error_code': fields.Integer(example = 404, description="Error code indicating the type of error"),
    'message': fields.String(example="Particular resource not found", description="Error message explaining the issue")
})
delete_traveller_model = api.model('DeleteTraveller', {
    'traveller_user_id': fields.Integer(
        required=True, 
        description="The user ID of the traveller to be deleted",
        example=2
    )
})
delete_traveller_by_passport_model = api.model('DeleteTravellerByPassport', {
    'passport_number': fields.String(
        required=True, 
        description="The passport number of the traveller to be deleted",
        example="A12345678"
    )
})
delete_vehicle_model = api.model('DeleteVehicle', {
    'vehicle_number': fields.String(
        required=True, 
        description="The license plate number of the vehicle to be deleted",
        example="SKR9859E"
    )
})
delete_vehicle_by_id_model = api.model('DeleteVehicleById', {
    'vehicle_id': fields.Integer(
        required=True, 
        description="The ID of the vehicle to be deleted",
        example=1
    )
})
update_preset_name_model = api.model('UpdatePresetName', {
    'preset_id': fields.Integer(
        required=True,
        description="The ID of the preset to update",
        example=2
    ),
    'preset_name': fields.String(
        required=True,
        description="The new name for the preset",
        example="Family Vacation"
    )
})
update_preset_travellers_model = api.model('UpdatePresetTravellers', {
    'preset_id': fields.Integer(
        required=True,
        description="The ID of the preset to update",
        example=2
    ),
    'traveller_ids': fields.List(
        fields.Integer,
        required=True,
        description="List of user IDs to be associated with the preset",
        example=[1, 2, 3]
    )
})
update_preset_model = api.model('UpdatePreset', {
    'preset_id': fields.Integer(
        required=True,
        description="The ID of the preset to update",
        example=2
    ),
    'preset_name': fields.String(
        required=True,
        description="The new name for the preset",
        example="Family Vacation"
    ),
    'traveller_ids': fields.List(
        fields.Integer,
        required=True,
        description="List of user IDs to be associated with the preset",
        example=[1, 2, 3]
    )
})
delete_preset_model = api.model('DeletePreset', {
    'preset_id': fields.Integer(
        required=True, 
        description="The ID of the preset to be deleted",
        example=1
    )
})
update_pass_travellers_model = api.model('UpdatePassTravellers', {
    'pass_id': fields.Integer(
        required=True,
        description="The ID of the pass to update",
        example=1
    ),
    'traveller_ids': fields.List(
        fields.Integer,
        required=True,
        description="List of user IDs to be associated with the pass",
        example=[1, 2, 3]
    )
})
delete_pass_model = api.model('DeletePass', {
    'pass_id': fields.Integer(
        required=True, 
        description="The ID of the pass to be deleted",
        example=1
    )
})
pass_history_with_travellers_model = api.model('PassHistoryWithTravellers', {
     'user_id': fields.Integer(required=True, example=1, description="Autogenerated id of the user"),
     "passes_utilized": fields.List(fields.Nested(api.model('PassHistoryWithTravellersDetails', {
         'pass_id': fields.Integer(readonly=True),
         'pass_date': fields.DateTime(required=True, description="Date when the pass was created"),
         'expiry_datetime': fields.DateTime(required=True, description="Expiry date and time of the pass"),
         'travellers': fields.List(fields.Nested(traveller_model_with_user_id), description="List of travellers associated with the pass")
     })))
 })
user_profile_with_id_model = api.model('UserProfileWithId', {
    'user_id': fields.Integer(required=True, example=1, description="ID of the user"),
    'first_name': fields.String(description="The first name of the user", example="John"),
    'middle_name': fields.String(description="The middle name of the user", example="David"),
    'last_name': fields.String(description="The last name of the user", example="Doe"),
    'date_of_birth': fields.String(description="The date of birth of the user in YYYY-MM-DD format", example="1990-01-01"),
    'nationality': fields.String(description="The nationality or passport issuing country of the user", example="American"),
    'passport_expiry': fields.String(description="The passport expiry date in YYYY-MM-DD format", example="2030-12-31"),
    'passport_number': fields.String(description="The passport number of the user", example="A12345678")
})
name_by_passport_request_model = api.model('NameByPassportRequest', {
    'passport_number': fields.String(
        required=True,
        description="The passport number to search for",
        example="A12345678"
    )
})

name_by_passport_response_model = api.model('NameByPassportResponse', {
    'first_name': fields.String(
        description="First name of the person",
        example="John"
    ),
    'middle_name': fields.String(
        description="Middle name of the person",
        example="David"
    ),
    'last_name': fields.String(
        description="Last name of the person",
        example="Smith"
    ),
    'full_name': fields.String(
        description="Combined full name",
        example="John David Smith"
    )
})
update_preset_travellers_passport_model = api.model('UpdatePresetTravellersPassport', {
    'preset_id': fields.Integer(
        required=True,
        description="The ID of the preset to update",
        example=2
    ),
    'preset_name': fields.String(
        required=True,
        description="The new name for the preset",
        example="Family Vacation"
    ),
    'passport_numbers': fields.List(
        fields.String,
        required=True,
        description="List of passport numbers to be associated with the preset",
        example=["A12345678", "B87654321", "UK7654321"]
    )
})

pass_details_by_id_model = api.model('PassDetailsById', {
    'pass_id': fields.Integer(readonly=True, description="ID of the pass"),
    'pass_date': fields.String(required=True, description="Date and time of the pass"),
    'expiry_datetime': fields.String(required=True, description="Expiry date and time of the pass"),
    'pass_utilized': fields.Boolean(required=True, description="Whether the pass has been utilized"),
    'passenger_count': fields.Integer(required=True, description="Number of passengers in the pass"),
    'travellers': fields.List(fields.Nested(traveller_model_with_user_id), description="List of travellers in the pass")
})

pass_details_request_model = api.model('PassDetailsRequest', {
    'pass_id': fields.Integer(required=True, description="ID of the pass to retrieve details for", example=1)
})

preset_with_users_and_count_model = api.model('PresetWithUsersAndCount', {
    'preset_id': fields.Integer(readonly=True),
    'preset_name': fields.String(required=True, description="Name of the preset"),
    'passenger_count': fields.Integer(required=True, description="Number of passengers in the preset"),
    'users': fields.List(fields.Nested(traveller_model_with_user_id))
})

retrieve_all_presets_with_count_model = api.model('AllPresetForUserWithCount', {
    'user_id': fields.Integer(required=True, example=1, description="Autogenerated id of the user"),
    'presets_created': fields.List(fields.Nested(preset_with_users_and_count_model))
})

update_pass_model = api.model('UpdatePass', {
    'pass_id': fields.Integer(
        required=True,
        description="The ID of the pass to update",
        example=1
    ),
    'pass_date': fields.String(
        required=True,
        description="New date and time for the pass (format: YYYY-MM-DD HH:MM:SS)",
        example="2023-07-20 10:00:00"
    ),
    'traveller_passport_numbers': fields.List(
        fields.String,
        required=True,
        description="List of passport numbers of travellers to be associated with the pass",
        example=["A12345678", "C98765432", "UK7654321"]
    )
})

pass_details_by_user_model = api.model('PassDetailsByUser', {
    'user_id': fields.Integer(readonly=True, description="ID of the user"),
    'passes': fields.List(fields.Nested(api.model('PassDetails', {
        'pass_id': fields.Integer(readonly=True, description="ID of the pass"),
        'pass_date': fields.String(required=True, description="Date and time of the pass"),
        'expiry_datetime': fields.String(required=True, description="Expiry date and time of the pass"),
        'pass_utilized': fields.Boolean(required=True, description="Whether the pass has been utilized"),
        'passenger_count': fields.Integer(required=True, description="Number of passengers in the pass"),
        'travellers': fields.List(fields.Nested(traveller_model_with_user_id), description="List of travellers in the pass")
    })))
})

batch_add_travellers_model = api.model('BatchAddTravellers', {
    'user_id': fields.Integer(
        required=True,
        description="The ID of the user to add travellers to",
        example=1
    ),
    'passport_numbers': fields.List(
        fields.String,
        required=True,
        description="List of passport numbers to check and add as travellers",
        example=["A12345678", "C98765432", "UK7654321"]
    )
})

batch_add_travellers_response_model = api.model('BatchAddTravellersResponse', {
    'user_id': fields.Integer(required=True, description="The ID of the user the travellers were added to"),
    'travellers_added': fields.List(fields.Nested(traveller_model_with_user_id), description="List of travellers that were added"),
    'travellers_already_present': fields.List(fields.Nested(traveller_model_with_user_id), description="List of travellers that were already in the user's list")
})

update_vehicle_model = api.model('UpdateVehicle', {
    'vehicle_id': fields.Integer(
        required=True,
        description="ID of the vehicle to update",
        example=1
    ),
    'user_vehicle_name': fields.String(
        required=True,
        description="New name/model for the vehicle",
        example="Toyota Corolla"
    ),
    'vehicle_number': fields.String(
        required=True,
        description="New license plate number for the vehicle",
        example="ABC123"
    )
})

update_vehicle_response_model = api.model('UpdateVehicleResponse', {
    'vehicle_id': fields.Integer(readonly=True, description="ID of the updated vehicle"),
    'user_vehicle_name': fields.String(required=True, description="Updated name/model of the vehicle"),
    'vehicle_number': fields.String(required=True, description="Updated license plate number"),
    'message': fields.String(required=True, description="Status message")
})


