from flask import Flask, request, render_template, redirect, url_for, send_from_directory, jsonify
from flask_restx import Api, Resource, fields
import os
import requests
from werkzeug.utils import secure_filename
from flask_sqlalchemy import SQLAlchemy
from flask_cors import CORS
from datetime import datetime, timedelta
from db_instance import db
from immigration_logic import immigration_walkthrough

from models import UserSensitiveInformation, Vehicle, UserVehicle, Preset, PresetTraveller, Pass, PassTraveller, UserTraveller
from mock_data import insert_mock_data
app = Flask(__name__)
CORS(app)
api = Api(app, version="1.0", title="Immigration API", description="A simple API for managing immigration workflows")
UPLOAD_FOLDER = 'uploads'
app.config['UPLOAD_FOLDER'] = UPLOAD_FOLDER
app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///immigration.db'
TOKEN = "210ed0449ee06e8d9bcee4a67c742814e4e7366e"
API_URL = "https://api.platerecognizer.com/v1/plate-reader/"
if not os.path.exists(UPLOAD_FOLDER):
    os.makedirs(UPLOAD_FOLDER)
db.init_app(app)
ns_user = api.namespace('users', description='User-related operations')
ns_vehicle = api.namespace('vehicles', description='Vehicle-related operations')
ns_preset = api.namespace('presets', description='Preset-related operations')
ns_pass = api.namespace('passes', description='Pass-related operations')
ns_traveller = api.namespace('travellers', description='Traveller management')
add_vehicle_model = api.model('AddVehicle', {
    'vehicle_number': fields.String(required=True, description="License plate number of the vehicle"),
    'user_vehicle_model': fields.String(required=True, description="Model of the vehicle user has entered")
})

add_vehicle_model_result = api.model('AddVehicleResult', {
    'user_vehicle': fields.Nested(api.model('UserVehicle', {
        'user_id': fields.Integer(readonly=True),
        'vehicle_id': fields.Integer(readonly=True),
        'vehicle_number': fields.String(required=True, description="Vehicle's license plate number"),
        'user_vehicle_model': fields.String(required=True, description="Model of the vehicle user has entered")
    }))
})

all_vehicles_model = api.model('AllUserVehicles', {
    'user_vehicle_id': fields.Integer(readonly=True),
    'user_vehicle_name': fields.String(required=True, description="Model name user has assigned to the vehicle"),
    'vehicle_id': fields.Integer(readonly=True),
    'vehicle_number': fields.String(required=True, description="Vehicle's license plate number")
})

preset_details_model = api.model('PresetDetailsWithUserId', {
    'user_id': fields.Integer(readonly=True, example=1, description="First name of the user"),
    'presets': fields.Nested(api.model('PresetDetails', {   
        'preset_id': fields.Integer(readonly=True),
        'preset_name': fields.String(required=True, description="The name of the preset"),
        'passenger_count': fields.Integer(required=True, description="The number of passengers in the preset")
    }))
})

traveller_model_with_user_id = api.model('User', {
    'user_id': fields.Integer(required=True, example=1, description="Autogenerated id of the user"),
    'first_name': fields.String(required=True, example="Alice", description="First name of the user"),
    'middle_name': fields.String(example="J", description="Middle name of the user"),
    'last_name': fields.String(required=True, example="Smith", description="Last name of the user"),
    'passport_number': fields.String(required=True, example="A12345678", description="The passport number of the user")
})

traveller_model = api.model('Traveller', {
    'first_name': fields.String(required=True, description="First name of the traveller"),
    'middle_name': fields.String(description="Middle name of the traveller"),
    'last_name': fields.String(required=True, description="Last name of the traveller"),
    'passport_number': fields.String(required=True, description="Passport number of the traveller")
})

user_travellers_model = api.model('UserTravellers', {
    'creator_user_id': fields.Integer(required=True, example=1, description="The ID of the user who created the traveller records"),
    'travellers': fields.List(fields.Nested(traveller_model_with_user_id), 
                              example=[{
                                  "user_id": 1,
                                  "first_name": "Alice",
                                  "middle_name": "J",
                                  "last_name": "Smith",
                                  "passport_number": "A12345678"
                              }],
                              description="A list of travellers added by the user")
})

preset_with_users_model = api.model('PresetWithUsers', {
    'preset_id': fields.Integer(readonly=True),
    'preset_name': fields.String(required=True, description="Name of the preset"),
    'users': fields.List(fields.Nested(traveller_model_with_user_id))
})

preset_with_users_model_2 = api.model('PresetWithUsers2', {
    'preset_name': fields.String(required=True, description="Name of the preset"),
    'user_id': fields.Integer(required=True, example=1, description="Autogenerated id of the user"),
    'travellers': fields.List(fields.Nested(traveller_model), description="List of travellers to be added to the preset")
})

retrieve_all_presets_for_user_model = api.model('AllPresetForUser', {
    'user_id': fields.Integer(required=True, example=1, description="Autogenerated id of the user"),
    'presets_created': fields.List(fields.Nested(preset_with_users_model))
})

preset_response_model = api.model('PresetResponse', {
    'preset_id': fields.Integer(readonly=True),
    'preset_name': fields.String(required=True, description="Name of the preset"),
    'created_by_user_id': fields.Integer(description="ID of the user who created the preset"),
    'travellers_added': fields.List(fields.Nested(traveller_model_with_user_id), description="List of travellers added to the preset")
})

pass_response_model = api.model('PassResponseWithUserId', {
    'user_id': fields.Integer(required=True, example=1, description="Autogenerated id of the user"),
    "passes": fields.Nested(api.model('PassResponse', {
        'pass_id': fields.Integer(readonly=True),
        'pass_date': fields.String(required=True, description="Date when the pass was created (in String, NOT Datetime)"),
        'expiry_datetime': fields.String(required=True, description="Expiry date of the pass (in String, NOT Datetime)"),
        'pass_utilized': fields.Boolean(required=True, description="Whether the pass has been utilized for immigration"),
        'travellers': fields.List(fields.Nested(traveller_model_with_user_id), description="List of travellers associated with the pass")
    }))
})

create_pass_model = api.model('CreatePass', {
    'creator_user_id': fields.Integer(required=True, description="User ID of the creator of the pass"),
    'pass_date': fields.String(required=True, description="Date and time of the pass creation (format: YYYY-MM-DD HH:MM:SS)"),
    'pass_utilized': fields.Boolean(required=True, description="Whether the pass is utilized or not"),
    'traveller_passport_numbers': fields.List(fields.String, required = True, description="List of traveller passport numbers")
})

pass_response_model_2 = api.model('PassResponse2', {
    'pass_id': fields.Integer(readonly=True),
    'creator_user_id': fields.Integer(required=True, description="User ID of the creator of the pass"),
    'pass_date': fields.String(required=True, description="Date and time of the pass creation"),
    'expiry_datetime': fields.String(required=True, description="Expiry date and time of the pass"),
    'pass_utilized': fields.Boolean(required=True, description="Whether the pass has been utilized"),
    'travellers_added': fields.List(fields.Nested(traveller_model_with_user_id), description="List of travellers added to the pass")
})

pass_history_model = api.model('PassHistoryWithUserId', {
    'user_id': fields.Integer(required=True, example=1, description="Autogenerated id of the user"),
    "passes_utilized": fields.List(fields.Nested(api.model('PassHistory', {
        'pass_id': fields.Integer(readonly=True),
        'pass_date': fields.DateTime(required=True, description="Date when the pass was created"),
        'expiry_datetime': fields.DateTime(required=True, description="Expiry date and time of the pass")
    })))
})

first_name_model = api.model('FirstName', {
    'first_name': fields.String(
        required=True, 
        description="The first name of the user",
        example="John"
    )
})

middle_name_model = api.model('MiddleName', {
    'middle_name': fields.String(
        required=True, 
        description="The middle name of the user",
        example="David"
    )
})

last_name_model = api.model('LastName', {
    'last_name': fields.String(
        required=True, 
        description="The last name of the user",
        example="Doe"
    )
})

dob_model = api.model('DateOfBirth', {
    'date_of_birth': fields.String(
        required=True, 
        description="The date of birth of the user in YYYY-MM-DD format", 
        example="1990-01-01"
    )
})

nationality_model = api.model('Nationality', {
    'nationality': fields.String(
        required=True, 
        description="The nationality or passport issuing country of the user",
        example="American"
    )
})

passport_expiry_model = api.model('PassportExpiry', {
    'passport_expiry': fields.String(
        required=True, 
        description="The passport expiry date in YYYY-MM-DD format",
        example="2030-12-31"
    )
})

passport_number_model = api.model('PassportNumber', {
    'passport_number': fields.String(
        required=True, 
        description="The passport number of the user",
        example="A12345678"
    )
})

user_profile_model = api.model('UserProfile', {
    'first_name': fields.String(
        description="The first name of the user", 
        example="John"
    ),
    'middle_name': fields.String(
        description="The middle name of the user", 
        example="David"
    ),
    'last_name': fields.String(
        description="The last name of the user", 
        example="Doe"
    ),
    'date_of_birth': fields.String(
        description="The date of birth of the user in YYYY-MM-DD format", 
        example="1990-01-01"
    ),
    'nationality': fields.String(
        description="The nationality or passport issuing country of the user", 
        example="American"
    ),
    'passport_expiry': fields.String(
        description="The passport expiry date in YYYY-MM-DD format", 
        example="2030-12-31"
    ),
    'passport_number': fields.String(
        description="The passport number of the user", 
        example="A12345678"
    )
})
success_message_model = api.model('FieldUpdateSuccess', {
    'message': fields.String(
        required=True, 
        description="Field showing successful update of particular field", 
        example="The field you are trying to modify has been updated"
    )
})

delete_message_model = api.model('DeleteMessage', {
    'message': fields.String(
        required=True, 
        description="Message indicating successful deletion of particular resource", 
        example="The resource you are trying to delete has been deleted"
    )
})
error_response_model_400 = api.model('ErrorResponse400', {
    'error_code': fields.Integer(example = 400, description="Error code indicating the type of error"),
    'message': fields.String(example="Required fields missing or data already in database", description="Error message explaining the issue")
})
error_response_model_404 = api.model('ErrorResponse404', {
    'error_code': fields.Integer(example = 404, description="Error code indicating the type of error"),
    'message': fields.String(example="Particular resource not found", description="Error message explaining the issue")
})
delete_traveller_model = api.model('DeleteTraveller', {
    'traveller_user_id': fields.Integer(
        required=True, 
        description="The user ID of the traveller to be deleted",
        example=2
    )
})
delete_traveller_by_passport_model = api.model('DeleteTravellerByPassport', {
    'passport_number': fields.String(
        required=True, 
        description="The passport number of the traveller to be deleted",
        example="A12345678"
    )
})
delete_vehicle_model = api.model('DeleteVehicle', {
    'vehicle_number': fields.String(
        required=True, 
        description="The license plate number of the vehicle to be deleted",
        example="SKR9859E"
    )
})
delete_vehicle_by_id_model = api.model('DeleteVehicleById', {
    'vehicle_id': fields.Integer(
        required=True, 
        description="The ID of the vehicle to be deleted",
        example=1
    )
})
update_preset_name_model = api.model('UpdatePresetName', {
    'preset_id': fields.Integer(
        required=True,
        description="The ID of the preset to update",
        example=2
    ),
    'preset_name': fields.String(
        required=True,
        description="The new name for the preset",
        example="Family Vacation"
    )
})
update_preset_travellers_model = api.model('UpdatePresetTravellers', {
    'preset_id': fields.Integer(
        required=True,
        description="The ID of the preset to update",
        example=2
    ),
    'traveller_ids': fields.List(
        fields.Integer,
        required=True,
        description="List of user IDs to be associated with the preset",
        example=[1, 2, 3]
    )
})
update_preset_model = api.model('UpdatePreset', {
    'preset_id': fields.Integer(
        required=True,
        description="The ID of the preset to update",
        example=2
    ),
    'preset_name': fields.String(
        required=True,
        description="The new name for the preset",
        example="Family Vacation"
    ),
    'traveller_ids': fields.List(
        fields.Integer,
        required=True,
        description="List of user IDs to be associated with the preset",
        example=[1, 2, 3]
    )
})
delete_preset_model = api.model('DeletePreset', {
    'preset_id': fields.Integer(
        required=True, 
        description="The ID of the preset to be deleted",
        example=1
    )
})
update_pass_travellers_model = api.model('UpdatePassTravellers', {
    'pass_id': fields.Integer(
        required=True,
        description="The ID of the pass to update",
        example=1
    ),
    'traveller_ids': fields.List(
        fields.Integer,
        required=True,
        description="List of user IDs to be associated with the pass",
        example=[1, 2, 3]
    )
})
delete_pass_model = api.model('DeletePass', {
    'pass_id': fields.Integer(
        required=True, 
        description="The ID of the pass to be deleted",
        example=1
    )
})
pass_history_with_travellers_model = api.model('PassHistoryWithTravellers', {
     'user_id': fields.Integer(required=True, example=1, description="Autogenerated id of the user"),
     "passes_utilized": fields.List(fields.Nested(api.model('PassHistoryWithTravellersDetails', {
         'pass_id': fields.Integer(readonly=True),
         'pass_date': fields.DateTime(required=True, description="Date when the pass was created"),
         'expiry_datetime': fields.DateTime(required=True, description="Expiry date and time of the pass"),
         'travellers': fields.List(fields.Nested(traveller_model_with_user_id), description="List of travellers associated with the pass")
     })))
 })
user_profile_with_id_model = api.model('UserProfileWithId', {
    'user_id': fields.Integer(required=True, example=1, description="ID of the user"),
    'first_name': fields.String(description="The first name of the user", example="John"),
    'middle_name': fields.String(description="The middle name of the user", example="David"),
    'last_name': fields.String(description="The last name of the user", example="Doe"),
    'date_of_birth': fields.String(description="The date of birth of the user in YYYY-MM-DD format", example="1990-01-01"),
    'nationality': fields.String(description="The nationality or passport issuing country of the user", example="American"),
    'passport_expiry': fields.String(description="The passport expiry date in YYYY-MM-DD format", example="2030-12-31"),
    'passport_number': fields.String(description="The passport number of the user", example="A12345678")
})
name_by_passport_request_model = api.model('NameByPassportRequest', {
    'passport_number': fields.String(
        required=True,
        description="The passport number to search for",
        example="A12345678"
    )
})

name_by_passport_response_model = api.model('NameByPassportResponse', {
    'first_name': fields.String(
        description="First name of the person",
        example="John"
    ),
    'middle_name': fields.String(
        description="Middle name of the person",
        example="David"
    ),
    'last_name': fields.String(
        description="Last name of the person",
        example="Smith"
    ),
    'full_name': fields.String(
        description="Combined full name",
        example="John David Smith"
    )
})
update_preset_travellers_passport_model = api.model('UpdatePresetTravellersPassport', {
    'preset_id': fields.Integer(
        required=True,
        description="The ID of the preset to update",
        example=2
    ),
    'preset_name': fields.String(
        required=True,
        description="The new name for the preset",
        example="Family Vacation"
    ),
    'passport_numbers': fields.List(
        fields.String,
        required=True,
        description="List of passport numbers to be associated with the preset",
        example=["A12345678", "B87654321", "UK7654321"]
    )
})

pass_details_by_id_model = api.model('PassDetailsById', {
    'pass_id': fields.Integer(readonly=True, description="ID of the pass"),
    'pass_date': fields.String(required=True, description="Date and time of the pass"),
    'expiry_datetime': fields.String(required=True, description="Expiry date and time of the pass"),
    'pass_utilized': fields.Boolean(required=True, description="Whether the pass has been utilized"),
    'passenger_count': fields.Integer(required=True, description="Number of passengers in the pass"),
    'travellers': fields.List(fields.Nested(traveller_model_with_user_id), description="List of travellers in the pass")
})

pass_details_request_model = api.model('PassDetailsRequest', {
    'pass_id': fields.Integer(required=True, description="ID of the pass to retrieve details for", example=1)
})

@app.route('/show-tables')
def view_tables():
    user_sensitive_data = UserSensitiveInformation.query.all()
    vehicle_data = Vehicle.query.all()
    user_vehicle_data = UserVehicle.query.all()
    pass_data = Pass.query.all()
    pass_traveller_data = PassTraveller.query.all()
    preset_data = Preset.query.all()
    preset_traveller_data = PresetTraveller.query.all()
    user_traveller_data = UserTraveller.query.all()

    return render_template('view_tables.html',
        user_sensitive_data=user_sensitive_data,
        vehicle_data=vehicle_data,
        user_vehicle_data=user_vehicle_data,
        pass_data=pass_data,
        pass_traveller_data=pass_traveller_data,
        preset_data=preset_data,
        preset_traveller_data=preset_traveller_data,
        user_traveller_data=user_traveller_data
    )



@ns_vehicle.route('/<int:user_id>/add-vehicle')
class UserVehicleResource(Resource):
    """Add a vehicle to a user."""

    @api.expect(add_vehicle_model)
    @api.response(200, 'Vehicle added successfully', add_vehicle_model_result)
    @api.response(400, 'Missing vehicle number or user vehicle model', error_response_model_400)
    @api.response(404, 'User or vehicle not found', error_response_model_404)
    def post(self, user_id):
        """Add a vehicle to the user"""

        user = UserSensitiveInformation.query.get(user_id)
        if not user:
            return {"error_code": 404, "message": "User not found"}, 404

        data = request.get_json()
        vehicle_number = data.get('vehicle_number')
        user_vehicle_model = data.get('user_vehicle_model') 

        if not vehicle_number:
            return {"error_code": 400, "message": "Missing vehicle_number"}, 400
        if not user_vehicle_model:
            return {"error_code": 400, "message": "Missing user_vehicle_model"}, 400

        vehicle = Vehicle.query.filter_by(vehicle_number=vehicle_number).first()
        if not vehicle:
            vehicle = Vehicle(vehicle_number=vehicle_number)
            db.session.add(vehicle)
            db.session.commit()
        user_vehicle = UserVehicle(
            user_id=user_id,
            vehicle_id=vehicle.vehicle_id,
            user_vehicle_model=user_vehicle_model
        )

        db.session.add(user_vehicle)
        db.session.commit()
        response = {
            "user_vehicle": {
                "user_id": user_id,
                "vehicle_id": vehicle.vehicle_id,
                "vehicle_number": vehicle.vehicle_number,
                "user_vehicle_model": user_vehicle_model
            }
        }
        return api.marshal(response, add_vehicle_model_result), 200

@ns_vehicle.route('/<int:user_id>/get-all-vehicles')
class UserVehiclesResource(Resource):
    """Get all vehicles associated with a user."""

    @api.response(200, 'Success', all_vehicles_model) 
    @api.response(404, 'User not found', error_response_model_404)
    def get(self, user_id):
        """Retrieve all vehicles linked to a user."""
        user = UserSensitiveInformation.query.get(user_id)
        if not user:
            return {"error_code": 404, "message": "User not found"}, 404
        user_vehicles = (
            db.session.query(UserVehicle, Vehicle)
            .join(Vehicle, UserVehicle.vehicle_id == Vehicle.vehicle_id)
            .filter(UserVehicle.user_id == user_id)
            .all()
        )
        vehicles_list = []
        for uv, v in user_vehicles:
            vehicles_list.append({
                'user_vehicle_id': uv.user_vehicle_id,
                'user_vehicle_name': uv.user_vehicle_model,
                'vehicle_id': v.vehicle_id,
                'vehicle_number': v.vehicle_number
            })

        return api.marshal(vehicles_list, all_vehicles_model), 200

@ns_vehicle.route('/<int:user_id>/delete-vehicle-by-number')
class DeleteVehicleResource(Resource):
    """Delete a vehicle from a user's vehicle list based on vehicle number"""

    @api.expect(delete_vehicle_model)
    @api.response(200, 'Vehicle deleted successfully', delete_message_model)
    @api.response(400, 'Required fields missing', error_response_model_400)
    @api.response(404, 'User, vehicle or association not found', error_response_model_404)
    def delete(self, user_id):
        """Delete a vehicle from the user's list of vehicles by vehicle number."""
        user = UserSensitiveInformation.query.get(user_id)
        if not user:
            return {"error_code": 404, "message": "User not found"}, 404
        data = request.get_json()
        vehicle_number = data.get("vehicle_number")

        if not vehicle_number:
            return {"error_code": 400, "message": "Vehicle number is required"}, 400
        vehicle = Vehicle.query.filter_by(vehicle_number=vehicle_number).first()
        if not vehicle:
            return {"error_code": 404, "message": "Vehicle with this number not found"}, 404

        vehicle_id = vehicle.vehicle_id
        user_vehicle = UserVehicle.query.filter_by(
            user_id=user_id,
            vehicle_id=vehicle_id
        ).first()

        if not user_vehicle:
            return {
                "error_code": 404, 
                "message": "This vehicle is not in your vehicle list"
            }, 404
        db.session.delete(user_vehicle)
        db.session.commit()

        return {"message": f"Vehicle with number {vehicle_number} removed from your vehicles list"}, 200


@ns_preset.route('/<int:user_id>/preset-summary')
class UserPresetsResource(Resource):
    @api.response(200, 'Success', preset_details_model)
    @api.response(404, 'Preset not found', error_response_model_404)
    def get(self, user_id):
        user = UserSensitiveInformation.query.get(user_id)
        if not user:
            return {"error": "User not found"}, 404

        presets = Preset.query.filter_by(user_id=user_id).all()

        presets_list = []
        for p in presets:
            passenger_count = db.session.query(PresetTraveller).filter_by(preset_id=p.preset_id).count()
            
            presets_list.append({
                "preset_id": p.preset_id,
                "preset_name": p.preset_name,
                "passenger_count": passenger_count
            })

        response = {
            "user_id": user_id,
            "presets": presets_list
        }

        return api.marshal(response, preset_details_model), 200

@ns_preset.route('/<int:user_id>/created-presets-with-users')
class UserCreatedPresetsWithUsersResource(Resource):
    @api.response(200, 'Success', retrieve_all_presets_for_user_model)
    @api.response(404, 'Preset not found', error_response_model_404)
    def get(self, user_id):
        user = UserSensitiveInformation.query.get(user_id)
        if not user:
            return {"error": "User not found"}, 404

        presets = (
            db.session.query(Preset.preset_id, Preset.preset_name)
            .filter(Preset.user_id == user_id)
            .all()
        )

        if not presets:
            return {"user_id": user_id, "presets_created": []}, 200

        presets_data = []
        for preset_id, preset_name in presets:
            preset_users = (
                db.session.query(
                    UserSensitiveInformation.user_id,
                    UserSensitiveInformation.first_name,
                    UserSensitiveInformation.middle_name,
                    UserSensitiveInformation.last_name,
                    UserSensitiveInformation.passport_number
                )
                .join(PresetTraveller, UserSensitiveInformation.user_id == PresetTraveller.user_id)
                .filter(PresetTraveller.preset_id == preset_id)
                .all()
            )

            users_list = [
                {
                    "user_id": u.user_id,
                    "first_name": u.first_name,
                    "middle_name": u.middle_name,
                    "last_name": u.last_name,
                    "passport_number": u.passport_number
                }
                for u in preset_users
            ]

            presets_data.append({
                "preset_id": preset_id,
                "preset_name": preset_name,
                "users": users_list
            })

        response = {
            "user_id": user_id,
            "presets_created": presets_data
        }
        
        return api.marshal(response, retrieve_all_presets_for_user_model), 200

@ns_preset.route('/<int:user_id>/created-presets-with-users-additional')
class UserCreatedPresetsWithUsersAdditionalResource(Resource):
    preset_with_users_and_count_model = api.model('PresetWithUsersAndCount', {
        'preset_id': fields.Integer(readonly=True),
        'preset_name': fields.String(required=True, description="Name of the preset"),
        'passenger_count': fields.Integer(required=True, description="Number of passengers in the preset"),
        'users': fields.List(fields.Nested(traveller_model_with_user_id))
    })

    retrieve_all_presets_with_count_model = api.model('AllPresetForUserWithCount', {
        'user_id': fields.Integer(required=True, example=1, description="Autogenerated id of the user"),
        'presets_created': fields.List(fields.Nested(preset_with_users_and_count_model))
    })

    @api.response(200, 'Success', retrieve_all_presets_with_count_model)
    @api.response(404, 'User not found', error_response_model_404)
    def get(self, user_id):
        user = UserSensitiveInformation.query.get(user_id)
        if not user:
            return {"error": "User not found"}, 404

        presets = (
            db.session.query(Preset.preset_id, Preset.preset_name)
            .filter(Preset.user_id == user_id)
            .all()
        )

        if not presets:
            return {"user_id": user_id, "presets_created": []}, 200

        presets_data = []
        for preset_id, preset_name in presets:
            preset_users = (
                db.session.query(
                    UserSensitiveInformation.user_id,
                    UserSensitiveInformation.first_name,
                    UserSensitiveInformation.middle_name,
                    UserSensitiveInformation.last_name,
                    UserSensitiveInformation.passport_number
                )
                .join(PresetTraveller, UserSensitiveInformation.user_id == PresetTraveller.user_id)
                .filter(PresetTraveller.preset_id == preset_id)
                .all()
            )

            users_list = [
                {
                    "user_id": u.user_id,
                    "first_name": u.first_name,
                    "middle_name": u.middle_name,
                    "last_name": u.last_name,
                    "passport_number": u.passport_number
                }
                for u in preset_users
            ]

            passenger_count = len(users_list)

            presets_data.append({
                "preset_id": preset_id,
                "preset_name": preset_name,
                "passenger_count": passenger_count,
                "users": users_list
            })

        response = {
            "user_id": user_id,
            "presets_created": presets_data
        }
        
        return api.marshal(response, self.retrieve_all_presets_with_count_model), 200

@ns_pass.route('/<int:user_id>/passes')
class UserPassesResource(Resource):
    @api.response(200, 'Success', pass_response_model)
    @api.response(404, 'User ID not found', error_response_model_404)
    def get(self, user_id):
        user = UserSensitiveInformation.query.get(user_id)
        if not user:
            return {"error": "User not found"}, 404

        passes = (
            db.session.query(
                Pass.pass_id,
                Pass.pass_date,
                Pass.expiry_datetime,
                Pass.pass_utilized
            )
            .filter(Pass.creator_user_id == user_id)
            .all()
        )

        passes_list = []
        for p in passes:
            travellers = (
                db.session.query(
                    UserSensitiveInformation.user_id,
                    UserSensitiveInformation.first_name,
                    UserSensitiveInformation.middle_name,
                    UserSensitiveInformation.last_name,
                    UserSensitiveInformation.passport_number
                )
                .join(PassTraveller, UserSensitiveInformation.user_id == PassTraveller.user_id)
                .filter(PassTraveller.pass_id == p.pass_id)
                .all()
            )

            travellers_list = [
                {
                    "user_id": t.user_id,
                    "first_name": t.first_name,
                    "middle_name": t.middle_name,
                    "last_name": t.last_name,
                    "passport_number": t.passport_number
                }
                for t in travellers
            ]

            passes_list.append({
                "pass_id": p.pass_id,
                "expiry_datetime": p.expiry_datetime.strftime("%Y-%m-%d %H:%M:%S"),
                "pass_date": p.pass_date.strftime("%Y-%m-%d %H:%M:%S"),
                "pass_utilized": p.pass_utilized,
                "travellers": travellers_list
            })

        response = {
            "user_id": user_id,
            "passes": passes_list
        }

        return api.marshal(response, pass_response_model), 200

@ns_pass.route('/create')
class CreatePassResource(Resource):
    @api.expect(create_pass_model)
    @api.response(200, 'Success', pass_response_model_2)
    @api.response(400, 'Missing required fields like Pass user id and pass date or invalid date format ', error_response_model_400)
    @api.response(404, 'Resource not found', error_response_model_404)
    def post(self):
        data = request.get_json()

        creator_user_id = data.get("creator_user_id")
        pass_date = data.get("pass_date")
        pass_utilized = data.get("pass_utilized", False)
        traveller_passport_numbers = data.get("traveller_passport_numbers", [])

        if not all([creator_user_id, pass_date]):
            return {"error": "Missing required fields - Pass user id and pass date"}, 400

        try:
            pass_date = datetime.strptime(pass_date, "%Y-%m-%d %H:%M:%S").date()
            expiry_datetime = pass_date + timedelta(hours=24)
    
        except ValueError:
            return {"error": "Invalid date format"}, 400

        new_pass = Pass(
            creator_user_id=creator_user_id,
            expiry_datetime=expiry_datetime,
            pass_date=pass_date,
            pass_utilized=pass_utilized,
        )

        db.session.add(new_pass)
        db.session.commit()

        pass_id = new_pass.pass_id

        travellers_added = []

        for passport_number in traveller_passport_numbers:
            user_sensitive = UserSensitiveInformation.query.filter_by(passport_number=passport_number).first()
            if not user_sensitive:
                return {"error": f"Traveller with passport number {passport_number} not found"}, 404

            traveller_user_id = user_sensitive.user_id

            pass_traveller = PassTraveller(pass_id=pass_id, user_id=traveller_user_id)
            db.session.add(pass_traveller)

            travellers_added.append({
                "user_id": traveller_user_id,
                "first_name": user_sensitive.first_name,
                "middle_name": user_sensitive.middle_name,
                "last_name": user_sensitive.last_name,
                "passport_number": passport_number
            })

        db.session.commit()

        response = {
            "pass_id": pass_id,
            "creator_user_id": creator_user_id,
            "pass_date": pass_date.strftime("%Y-%m-%d %H:%M:%S"),
            "expiry_datetime": expiry_datetime.strftime("%Y-%m-%d %H:%M:%S"),
            "pass_utilized": pass_utilized,
            "travellers_added": travellers_added
        }

        return api.marshal(response, pass_response_model_2), 200

@ns_pass.route('/<int:user_id>/passes-history-all')
class UserPassHistoryWithTravellersResource(Resource):
    @api.response(200, 'Success', pass_history_with_travellers_model)
    @api.response(404, 'Resource not found', error_response_model_404)
    def get(self, user_id):
        user = UserSensitiveInformation.query.get(user_id)
        if not user:
            return {"error_code": 404, "message": "User not found"}, 404

        utilized_passes = (
            db.session.query(
                Pass.pass_id,
                Pass.pass_date,
                Pass.expiry_datetime
            )
            .filter(Pass.creator_user_id == user_id, Pass.pass_utilized == True)
            .all()
        )

        passes_list = []
        for p in utilized_passes:
            travellers = (
                db.session.query(
                    UserSensitiveInformation.user_id,
                    UserSensitiveInformation.first_name,
                    UserSensitiveInformation.middle_name,
                    UserSensitiveInformation.last_name,
                    UserSensitiveInformation.passport_number
                )
                    .join(PassTraveller, UserSensitiveInformation.user_id == PassTraveller.user_id)
                    .filter(PassTraveller.pass_id == p.pass_id)
                .all()
            )
            travellers_list = [
            {
                "user_id": t.user_id,
                "first_name": t.first_name,
                "middle_name": t.middle_name,
                "last_name": t.last_name,
                "passport_number": t.passport_number
            }
            for t in travellers
        ]
            passes_list.append({
                "pass_id": p.pass_id,
                "pass_date": p.pass_date,
                "expiry_datetime": p.expiry_datetime,
                "travellers": travellers_list
            })

            response = {
            "user_id": user_id,
            "passes_utilized": passes_list
        }
        return api.marshal(response, pass_history_with_travellers_model), 200


@ns_user.route('/retrieve-name-by-passport')
class RetrieveNameByPassportResource(Resource):
    """Retrieve name information based on passport number."""

    @api.expect(name_by_passport_request_model)
    @api.response(200, 'Success', name_by_passport_response_model)
    @api.response(400, 'Missing passport number', error_response_model_400)
    @api.response(404, 'User or passport not found', error_response_model_404)
    def post(self):
        """Retrieve first name, middle name, last name and full name by passport number."""
        data = request.get_json()
        passport_number = data.get("passport_number")

        if not passport_number:
            return {"error_code": 400, "message": "Passport number is required"}, 400
        person = UserSensitiveInformation.query.filter_by(passport_number=passport_number).first()
        if not person:
            return {"error_code": 404, "message": "Person with this passport number not found"}, 404
        name_parts = []
        if person.first_name:
            name_parts.append(person.first_name)
        if person.middle_name:
            name_parts.append(person.middle_name)
        if person.last_name:
            name_parts.append(person.last_name)
        
        full_name = " ".join(name_parts)
        response = {
            "first_name": person.first_name,
            "middle_name": person.middle_name,
            "last_name": person.last_name,
            "full_name": full_name
        }

        return api.marshal(response, name_by_passport_response_model), 200

@ns_user.route('/<int:user_id>/profile')
class UserProfileResource(Resource):
    """Retrieve the profile of the user."""

    @api.response(200, 'User profile retrieved successfully', user_profile_model)
    @api.response(404, 'User not found', error_response_model_404)
    def get(self, user_id):
        """Get all the information of the user."""
        user = UserSensitiveInformation.query.get(user_id)

        if not user:
            return {"error_code": 404, "message": "User not found"}, 404
        profile_data = {
            "first_name": user.first_name if user.first_name else None,
            "middle_name": user.middle_name if user.middle_name else None,
            "last_name": user.last_name if user.last_name else None,
            "date_of_birth": user.date_of_birth.strftime("%Y-%m-%d") if user.date_of_birth else None,
            "nationality": user.passport_issuing_country if user.passport_issuing_country else None,
            "passport_expiry": user.passport_expiry.strftime("%Y-%m-%d") if user.passport_expiry else None,
            "passport_number": user.passport_number if user.passport_number else None
        }

        return api.marshal(profile_data, user_profile_model), 200

@ns_traveller.route('/<int:user_id>/get-travellers')
class UserTravellersResource(Resource):
    """Get all travellers (that are not associated with pass/preset) for a user."""

    @api.response(200, 'Travellers retrieved successfully', user_travellers_model)
    @api.response(404, 'User not found', error_response_model_404)
    @api.response(400, 'Bad request due to incorrect data', error_response_model_400)
    def get(self, user_id):
        """Retrieve all travellers added by the user that are not associated with a pass or preset."""
        creator = UserSensitiveInformation.query.get(user_id)
        if not creator:
            return {"error_code": 404, "message": "User not found"}, 404
        travellers = (
            db.session.query(
                UserSensitiveInformation.user_id,
                UserSensitiveInformation.first_name,
                UserSensitiveInformation.middle_name,
                UserSensitiveInformation.last_name,
                UserSensitiveInformation.passport_number
            )
            .join(UserTraveller, UserSensitiveInformation.user_id == UserTraveller.traveller_id)
            .filter(UserTraveller.creator_user_id == user_id)
            .all()
        )
        traveller_list = [
            {
                "user_id": t.user_id,
                "first_name": t.first_name,
                "middle_name": t.middle_name,
                "last_name": t.last_name,
                "passport_number": t.passport_number
            }
            for t in travellers
        ]
        response = {
            "creator_user_id": user_id,
            "travellers": traveller_list
        }
        return api.marshal(response, user_travellers_model), 200

@ns_traveller.route('/<int:user_id>/add-traveller')
class AddTravellerResource(Resource):
    """Add a traveller (not associated with pass/preset) for a user."""

    @api.expect(passport_number_model)
    @api.response(201, 'Traveller added successfully', user_travellers_model)
    @api.response(400, 'Required fields missing or data already in database', error_response_model_400)
    @api.response(404, 'Resource not found', error_response_model_404)
    def post(self, user_id):    
        """Add a traveller for the user."""
        creator = UserSensitiveInformation.query.get(user_id)
        if not creator:
            return {"error_code": 404, "message": "Creator user not found"}, 404
        data = request.get_json()
        passport_number = data.get("passport_number")

        if not passport_number:
            return {"error_code": 400, "message": "Passport number is required"}, 400
        traveller = UserSensitiveInformation.query.filter_by(passport_number=passport_number).first()
        
        if not traveller:
            return {"error_code": 404, "message": "Traveller with this passport number not found"}, 404

        traveller_id = traveller.user_id
        existing_entry = UserTraveller.query.filter_by(creator_user_id=user_id, traveller_id=traveller_id).first()
        if existing_entry:
            return {"error_code": 400, "message": "Traveller already added"}, 400
        new_traveller = UserTraveller(creator_user_id=user_id, traveller_id=traveller_id)
        db.session.add(new_traveller)
        db.session.commit()
        response = {
            "creator_user_id": user_id,
            "travellers": {
                "user_id": traveller.user_id,
                "first_name": traveller.first_name,
                "middle_name": traveller.middle_name,
                "last_name": traveller.last_name,
                "passport_number": traveller.passport_number
            }
        }

        return api.marshal(response, user_travellers_model), 201

@ns_traveller.route('/<int:user_id>/delete-traveller-by-passport')
class DeleteTravellerByPassportResource(Resource):
    """Delete a traveller from a user's traveller list based on the traveller's passport number"""

    @api.expect(delete_traveller_by_passport_model)
    @api.response(200, 'Traveller deleted successfully', success_message_model)
    @api.response(400, 'Required fields missing', error_response_model_400)
    @api.response(404, 'User or traveller not found', error_response_model_404)
    def delete(self, user_id):
        """Delete a traveller from the user's list of travellers by passport number."""
        creator_user = UserSensitiveInformation.query.get(user_id)
        if not creator_user:
            return {"error_code": 404, "message": "Creator user not found"}, 404
        data = request.get_json()
        passport_number = data.get("passport_number")

        if not passport_number:
            return {"error_code": 400, "message": "Passport number is required"}, 400
        traveller = UserSensitiveInformation.query.filter_by(passport_number=passport_number).first()
        if not traveller:
            return {"error_code": 404, "message": "Traveller with this passport number not found"}, 404

        traveller_id = traveller.user_id
        user_traveller = UserTraveller.query.filter_by(
            creator_user_id=user_id,
            traveller_id=traveller_id
        ).first()

        if not user_traveller:
            return {
                "error_code": 404, 
                "message": "This traveller is not in your traveller list"
            }, 404
        db.session.delete(user_traveller)
        db.session.commit()

        return {"message": f"Traveller with passport number {passport_number} deleted successfully"}, 200

@ns_preset.route('/<int:user_id>/delete-preset')
class DeletePresetResource(Resource):
    @api.expect(delete_preset_model)
    @api.response(200, 'Preset deleted successfully', success_message_model)
    @api.response(400, 'Required fields missing', error_response_model_400)
    @api.response(404, 'User, preset not found, or preset does not belong to user', error_response_model_404)
    def delete(self, user_id):
        user = UserSensitiveInformation.query.get(user_id)
        if not user:
            return {"error_code": 404, "message": "User not found"}, 404

        data = request.get_json()
        preset_id = data.get("preset_id")

        if not preset_id:
            return {"error_code": 400, "message": "Preset ID is required"}, 400

        preset = Preset.query.get(preset_id)
        if not preset:
            return {"error_code": 404, "message": "Preset not found"}, 404

        if preset.user_id != user_id:
            return {
                "error_code": 404, 
                "message": "This preset does not belong to the specified user"
            }, 404

        try:
            PresetTraveller.query.filter_by(preset_id=preset_id).delete()
            
            db.session.delete(preset)
            db.session.commit()

            return {"message": f"Preset with ID {preset_id} has been deleted successfully"}, 200

        except Exception as e:
            db.session.rollback()
            return {"error_code": 400, "message": f"Error deleting preset: {str(e)}"}, 400

@ns_pass.route('/<int:user_id>/delete-pass')
class DeletePassResource(Resource):
    @api.expect(delete_pass_model)
    @api.response(200, 'Pass deleted successfully', success_message_model)
    @api.response(400, 'Required fields missing', error_response_model_400)
    @api.response(404, 'User, pass not found, or pass does not belong to user', error_response_model_404)
    def delete(self, user_id):
        user = UserSensitiveInformation.query.get(user_id)
        if not user:
            return {"error_code": 404, "message": "User not found"}, 404

        data = request.get_json()
        pass_id = data.get("pass_id")

        if not pass_id:
            return {"error_code": 400, "message": "Pass ID is required"}, 400

        pass_entry = Pass.query.get(pass_id)
        if not pass_entry:
            return {"error_code": 404, "message": "Pass not found"}, 404

        if pass_entry.creator_user_id != user_id:
            return {
                "error_code": 404, 
                "message": "This pass does not belong to the specified user"
            }, 404

        try:
            PassTraveller.query.filter_by(pass_id=pass_id).delete()
            
            db.session.delete(pass_entry)
            db.session.commit()

            return {"message": f"Pass with ID {pass_id} has been deleted successfully"}, 200

        except Exception as e:
            db.session.rollback()
            return {"error_code": 400, "message": f"Error deleting pass: {str(e)}"}, 400

@ns_user.route('/<int:user_id>/update-profile')
@api.param('user_id', 'The user identifier')
class UpdateUserProfileResource(Resource):
    @api.expect(user_profile_model)
    @api.response(200, 'User profile updated successfully', user_profile_with_id_model)
    @api.response(400, 'Invalid data format', error_response_model_400)
    @api.response(404, 'User ID not found', error_response_model_404)
    def put(self, user_id):
        data = request.get_json()

        user = UserSensitiveInformation.query.get(user_id)
        if not user:
            return {"error_code": 404, "message": "User not found"}, 404

        try:
            if 'first_name' in data and data['first_name']:
                user.first_name = data['first_name']

            if 'middle_name' in data and data['middle_name']:
                user.middle_name = data['middle_name']

            if 'last_name' in data and data['last_name']:
                user.last_name = data['last_name']

            if 'date_of_birth' in data and data['date_of_birth']:
                try:
                    user.date_of_birth = datetime.strptime(data['date_of_birth'], "%Y-%m-%d").date()
                except ValueError:
                    return {"error_code": 400, "message": "Invalid date format for date_of_birth. Use YYYY-MM-DD"}, 400

            if 'nationality' in data and data['nationality']:
                user.passport_issuing_country = data['nationality']

            if 'passport_expiry' in data and data['passport_expiry']:
                try:
                    user.passport_expiry = datetime.strptime(data['passport_expiry'], "%Y-%m-%d")
                except ValueError:
                    return {"error_code": 400, "message": "Invalid date format for passport_expiry. Use YYYY-MM-DD"}, 400

            if 'passport_number' in data and data['passport_number']:
                user.passport_number = data['passport_number']

            db.session.commit()

            response_data = {
                "user_id": user_id,
                "first_name": user.first_name,
                "middle_name": user.middle_name,
                "last_name": user.last_name,
                "date_of_birth": user.date_of_birth.strftime("%Y-%m-%d") if user.date_of_birth else None,
                "nationality": user.passport_issuing_country,
                "passport_expiry": user.passport_expiry.strftime("%Y-%m-%d") if user.passport_expiry else None,
                "passport_number": user.passport_number
            }

            return api.marshal(response_data, user_profile_with_id_model), 200

        except Exception as e:
            db.session.rollback()
            return {"error_code": 400, "message": f"Error updating user profile: {str(e)}"}, 400

@app.route('/reset')
def reset_database():
    """Reset the database by dropping all tables and reinserting mock data."""
    try:
        with app.app_context():
            db.drop_all()
            db.create_all()
            insert_mock_data()
            
        return jsonify({
            "message": "Database reset successful",
            "status": "success"
        }), 200
        
    except Exception as e:
        return jsonify({
            "message": f"Error resetting database: {str(e)}",
            "status": "error"
        }), 500



@ns_pass.route('/details')
class PassDetailsByIdResource(Resource):
    """Get details for a specific pass ID."""

    @api.expect(pass_details_request_model)
    @api.response(200, 'Success', pass_details_by_id_model)
    @api.response(400, 'Missing pass ID', error_response_model_400)
    @api.response(404, 'Pass not found', error_response_model_404)
    def post(self):
        """Retrieve details of a specific pass including pass date, expiry datetime, travellers, and passenger count."""
        data = request.get_json()
        pass_id = data.get("pass_id")
        if not pass_id:
            return {"error_code": 400, "message": "Pass ID is required"}, 400
        pass_entry = Pass.query.get(pass_id)
        if not pass_entry:
            return {"error_code": 404, "message": "Pass not found"}, 404
        travellers = (
            db.session.query(
                UserSensitiveInformation.user_id,
                UserSensitiveInformation.first_name,
                UserSensitiveInformation.middle_name,
                UserSensitiveInformation.last_name,
                UserSensitiveInformation.passport_number
            )
            .join(PassTraveller, UserSensitiveInformation.user_id == PassTraveller.user_id)
            .filter(PassTraveller.pass_id == pass_id)
            .all()
        )
        travellers_list = [
            {
                "user_id": t.user_id,
                "first_name": t.first_name,
                "middle_name": t.middle_name,
                "last_name": t.last_name,
                "passport_number": t.passport_number
            }
            for t in travellers
        ]
        passenger_count = len(travellers_list)
        response = {
            "pass_id": pass_id,
            "pass_date": pass_entry.pass_date.strftime("%Y-%m-%d %H:%M:%S"),
            "expiry_datetime": pass_entry.expiry_datetime.strftime("%Y-%m-%d %H:%M:%S"),
            "pass_utilized": pass_entry.pass_utilized,
            "passenger_count": passenger_count,
            "travellers": travellers_list
        }

        return api.marshal(response, pass_details_by_id_model), 200
update_pass_model = api.model('UpdatePass', {
    'pass_id': fields.Integer(
        required=True,
        description="The ID of the pass to update",
        example=1
    ),
    'pass_date': fields.String(
        required=True,
        description="New date and time for the pass (format: YYYY-MM-DD HH:MM:SS)",
        example="2023-07-20 10:00:00"
    ),
    'traveller_passport_numbers': fields.List(
        fields.String,
        required=True,
        description="List of passport numbers of travellers to be associated with the pass",
        example=["A12345678", "C98765432", "UK7654321"]
    )
})

@ns_pass.route('/update')
class UpdatePassResource(Resource):
    """Update a pass with a new date and list of travellers."""

    @api.expect(update_pass_model)
    @api.response(200, 'Pass updated successfully', pass_details_by_id_model)
    @api.response(400, 'Required fields missing or invalid date format', error_response_model_400)
    @api.response(404, 'Pass or traveller not found', error_response_model_404)
    def put(self):
        """Update a pass with a new date and list of travellers by passport numbers."""
        data = request.get_json()
        pass_id = data.get("pass_id")
        pass_date_str = data.get("pass_date")
        traveller_passport_numbers = data.get("traveller_passport_numbers", [])
        if not pass_id:
            return {"error_code": 400, "message": "Pass ID is required"}, 400
        
        if not pass_date_str:
            return {"error_code": 400, "message": "Pass date is required"}, 400
        
        if not isinstance(traveller_passport_numbers, list):
            return {"error_code": 400, "message": "traveller_passport_numbers must be a list"}, 400
        pass_entry = Pass.query.get(pass_id)
        if not pass_entry:
            return {"error_code": 404, "message": "Pass not found"}, 404
        try:
            new_pass_date = datetime.strptime(pass_date_str, "%Y-%m-%d %H:%M:%S")
            new_expiry_datetime = new_pass_date + timedelta(hours=24)
        except ValueError:
            return {"error_code": 400, "message": "Invalid date format. Use YYYY-MM-DD HH:MM:SS"}, 400
        travellers = []
        for passport_number in traveller_passport_numbers:
            traveller = UserSensitiveInformation.query.filter_by(passport_number=passport_number).first()
            if not traveller:
                return {
                    "error_code": 404, 
                    "message": f"Traveller with passport number {passport_number} not found"
                }, 404
            travellers.append(traveller)

        try:
            pass_entry.pass_date = new_pass_date
            pass_entry.expiry_datetime = new_expiry_datetime
            PassTraveller.query.filter_by(pass_id=pass_id).delete()
            travellers_list = []
            for traveller in travellers:
                pass_traveller = PassTraveller(pass_id=pass_id, user_id=traveller.user_id)
                db.session.add(pass_traveller)
                travellers_list.append({
                    "user_id": traveller.user_id,
                    "first_name": traveller.first_name,
                    "middle_name": traveller.middle_name,
                    "last_name": traveller.last_name,
                    "passport_number": traveller.passport_number
                })
            db.session.commit()
            passenger_count = len(travellers_list)
            response = {
                "pass_id": pass_id,
                "pass_date": pass_entry.pass_date.strftime("%Y-%m-%d %H:%M:%S"),
                "expiry_datetime": pass_entry.expiry_datetime.strftime("%Y-%m-%d %H:%M:%S"),
                "pass_utilized": pass_entry.pass_utilized,
                "passenger_count": passenger_count,
                "travellers": travellers_list
            }

            return api.marshal(response, pass_details_by_id_model), 200

        except Exception as e:
            db.session.rollback()
            return {"error_code": 400, "message": f"Error updating pass: {str(e)}"}, 400
pass_details_by_user_model = api.model('PassDetailsByUser', {
    'user_id': fields.Integer(readonly=True, description="ID of the user"),
    'passes': fields.List(fields.Nested(api.model('PassDetails', {
        'pass_id': fields.Integer(readonly=True, description="ID of the pass"),
        'pass_date': fields.String(required=True, description="Date and time of the pass"),
        'expiry_datetime': fields.String(required=True, description="Expiry date and time of the pass"),
        'pass_utilized': fields.Boolean(required=True, description="Whether the pass has been utilized"),
        'passenger_count': fields.Integer(required=True, description="Number of passengers in the pass"),
        'travellers': fields.List(fields.Nested(traveller_model_with_user_id), description="List of travellers in the pass")
    })))
})

@ns_pass.route('/<int:user_id>/details')
class UserPassDetailsResource(Resource):
    """Get details for all passes created by a user."""

    @api.response(200, 'Success', pass_details_by_user_model)
    @api.response(404, 'User not found', error_response_model_404)
    def get(self, user_id):
        """Retrieve details of all passes created by a user, including pass date, expiry datetime, travellers, and passenger count."""
        user = UserSensitiveInformation.query.get(user_id)
        if not user:
            return {"error_code": 404, "message": "User not found"}, 404
        pass_id = request.args.get('pass_id', None)
        passes_query = Pass.query.filter(Pass.creator_user_id == user_id)
        if pass_id is not None:
            try:
                pass_id = int(pass_id)
                passes_query = passes_query.filter(Pass.pass_id == pass_id)
            except ValueError:
                return {"error_code": 400, "message": "Invalid pass_id parameter"}, 400
        
        passes = passes_query.all()
        passes_list = []
        for pass_entry in passes:
            travellers = (
                db.session.query(
                    UserSensitiveInformation.user_id,
                    UserSensitiveInformation.first_name,
                    UserSensitiveInformation.middle_name,
                    UserSensitiveInformation.last_name,
                    UserSensitiveInformation.passport_number
                )
                .join(PassTraveller, UserSensitiveInformation.user_id == PassTraveller.user_id)
                .filter(PassTraveller.pass_id == pass_entry.pass_id)
                .all()
            )
            travellers_list = [
                {
                    "user_id": t.user_id,
                    "first_name": t.first_name,
                    "middle_name": t.middle_name,
                    "last_name": t.last_name,
                    "passport_number": t.passport_number
                }
                for t in travellers
            ]
            passenger_count = len(travellers_list)
            passes_list.append({
                "pass_id": pass_entry.pass_id,
                "pass_date": pass_entry.pass_date.strftime("%Y-%m-%d %H:%M:%S"),
                "expiry_datetime": pass_entry.expiry_datetime.strftime("%Y-%m-%d %H:%M:%S"),
                "pass_utilized": pass_entry.pass_utilized,
                "passenger_count": passenger_count,
                "travellers": travellers_list
            })
        response = {
            "user_id": user_id,
            "passes": passes_list
        }

        return api.marshal(response, pass_details_by_user_model), 200
batch_add_travellers_model = api.model('BatchAddTravellers', {
    'user_id': fields.Integer(
        required=True,
        description="The ID of the user to add travellers to",
        example=1
    ),
    'passport_numbers': fields.List(
        fields.String,
        required=True,
        description="List of passport numbers to check and add as travellers",
        example=["A12345678", "C98765432", "UK7654321"]
    )
})

batch_add_travellers_response_model = api.model('BatchAddTravellersResponse', {
    'user_id': fields.Integer(required=True, description="The ID of the user the travellers were added to"),
    'travellers_added': fields.List(fields.Nested(traveller_model_with_user_id), description="List of travellers that were added"),
    'travellers_already_present': fields.List(fields.Nested(traveller_model_with_user_id), description="List of travellers that were already in the user's list")
})

@ns_traveller.route('/batch-add-travellers')
class BatchAddTravellersResource(Resource):
    """Check if travellers exist in a user's list and add them if not."""

    @api.expect(batch_add_travellers_model)
    @api.response(200, 'Travellers processed successfully', batch_add_travellers_response_model)
    @api.response(400, 'Required fields missing', error_response_model_400)
    @api.response(404, 'User or traveller not found', error_response_model_404)
    def post(self):
        """Check if travellers with given passport numbers are in a user's list and add them if not."""
        data = request.get_json()
        user_id = data.get("user_id")
        passport_numbers = data.get("passport_numbers", [])
        if not user_id:
            return {"error_code": 400, "message": "User ID is required"}, 400
        
        if not isinstance(passport_numbers, list) or not passport_numbers:
            return {"error_code": 400, "message": "Passport numbers list is required and cannot be empty"}, 400
        creator = UserSensitiveInformation.query.get(user_id)
        if not creator:
            return {"error_code": 404, "message": "User not found"}, 404
        existing_traveller_ids = db.session.query(UserTraveller.traveller_id)\
            .filter(UserTraveller.creator_user_id == user_id)\
            .all()
        existing_traveller_ids = [t[0] for t in existing_traveller_ids]
        
        travellers_added = []
        travellers_already_present = []
        
        try:
            for passport_number in passport_numbers:
                traveller = UserSensitiveInformation.query.filter_by(passport_number=passport_number).first()
                
                if not traveller:
                    return {"error_code": 404, "message": f"Traveller with passport number {passport_number} not found"}, 404
                if traveller.user_id in existing_traveller_ids:
                    travellers_already_present.append({
                        "user_id": traveller.user_id,
                        "first_name": traveller.first_name,
                        "middle_name": traveller.middle_name,
                        "last_name": traveller.last_name,
                        "passport_number": traveller.passport_number
                    })
                else:
                    new_traveller = UserTraveller(creator_user_id=user_id, traveller_id=traveller.user_id)
                    db.session.add(new_traveller)
                    
                    travellers_added.append({
                        "user_id": traveller.user_id,
                        "first_name": traveller.first_name,
                        "middle_name": traveller.middle_name,
                        "last_name": traveller.last_name,
                        "passport_number": traveller.passport_number
                    })
            db.session.commit()
            response = {
                "user_id": user_id,
                "travellers_added": travellers_added,
                "travellers_already_present": travellers_already_present
            }
            
            return api.marshal(response, batch_add_travellers_response_model), 200
            
        except Exception as e:
            db.session.rollback()
            return {"error_code": 400, "message": f"Error processing travellers: {str(e)}"}, 400
update_vehicle_model = api.model('UpdateVehicle', {
    'vehicle_id': fields.Integer(
        required=True,
        description="ID of the vehicle to update",
        example=1
    ),
    'user_vehicle_name': fields.String(
        required=True,
        description="New name/model for the vehicle",
        example="Toyota Corolla"
    ),
    'vehicle_number': fields.String(
        required=True,
        description="New license plate number for the vehicle",
        example="ABC123"
    )
})

update_vehicle_response_model = api.model('UpdateVehicleResponse', {
    'vehicle_id': fields.Integer(readonly=True, description="ID of the updated vehicle"),
    'user_vehicle_name': fields.String(required=True, description="Updated name/model of the vehicle"),
    'vehicle_number': fields.String(required=True, description="Updated license plate number"),
    'message': fields.String(required=True, description="Status message")
})

@ns_preset.route('/create')
class CreatePresetResource(Resource):
    @api.expect(preset_with_users_model_2)
    @api.response(200, 'Success', preset_response_model)
    @api.response(400, 'Preset name or User ID not given in input', error_response_model_400)
    @api.response(404, 'Creator User ID/Passport number of one of the travellers not found', error_response_model_404)
    def post(self):
        data = request.get_json()

        preset_name = data.get("preset_name")
        user_id = data.get("user_id")
        travellers = data.get("travellers", [])

        if not preset_name:
            return {"error": "Preset name is required"}, 400
        if not user_id:
            return {"error": "User ID is required"}, 400

        creator = UserSensitiveInformation.query.get(user_id)
        if not creator:
            return {"error": f"User with user ID {user_id} not found"}, 404

        new_preset = Preset(preset_name=preset_name, user_id=user_id)
        db.session.add(new_preset)
        db.session.commit()

        preset_id = new_preset.preset_id

        travellers_added = []

        for traveller in travellers:
            passport_number = traveller.get("passport_number")
            given_first_name = traveller.get("first_name")
            given_middle_name = traveller.get("middle_name")
            given_last_name = traveller.get("last_name")

            user_sensitive = UserSensitiveInformation.query.filter_by(passport_number=passport_number).first()
            if not user_sensitive:
                return {"error": f"Traveller with passport number {passport_number} not found"}, 404

            traveller_user_id = user_sensitive.user_id

            preset_traveller = PresetTraveller(preset_id=preset_id, user_id=traveller_user_id)
            db.session.add(preset_traveller)

            travellers_added.append({
                "user_id": traveller_user_id,
                "first_name": given_first_name,
                "middle_name": given_middle_name,
                "last_name": given_last_name,
                "passport_number": passport_number
            })

        db.session.commit()

        response = {
            "preset_id": preset_id,
            "preset_name": preset_name,
            "created_by_user_id": user_id,
            "travellers_added": travellers_added
        }

        return api.marshal(response, preset_response_model), 200

@ns_preset.route('/<int:user_id>/update-preset-travellers-passport')
class UpdatePresetTravellersPassportResource(Resource):
    @api.expect(update_preset_travellers_passport_model)
    @api.response(200, 'Preset travellers updated successfully', preset_response_model)
    @api.response(400, 'Required fields missing', error_response_model_400)
    @api.response(404, 'User, preset or traveller not found, or preset does not belong to user', error_response_model_404)
    def put(self, user_id):
        user = UserSensitiveInformation.query.get(user_id)
        if not user:
            return {"error_code": 404, "message": "User not found"}, 404

        data = request.get_json()
        preset_id = data.get("preset_id")
        preset_name = data.get("preset_name")
        passport_numbers = data.get("passport_numbers", [])

        if not preset_id:
            return {"error_code": 400, "message": "Preset ID is required"}, 400
        
        if not preset_name:
            return {"error_code": 400, "message": "Preset name is required"}, 400
        
        if not isinstance(passport_numbers, list):
            return {"error_code": 400, "message": "passport_numbers must be a list"}, 400

        preset = Preset.query.get(preset_id)
        if not preset:
            return {"error_code": 404, "message": "Preset not found"}, 404

        if preset.user_id != user_id:
            return {
                "error_code": 404, 
                "message": "This preset does not belong to the specified user"
            }, 404

        travellers = []
        for passport_number in passport_numbers:
            traveller = UserSensitiveInformation.query.filter_by(passport_number=passport_number).first()
            if not traveller:
                return {
                    "error_code": 404, 
                    "message": f"Traveller with passport number {passport_number} not found"
                }, 404
            travellers.append(traveller)

        try:
            preset.preset_name = preset_name

            PresetTraveller.query.filter_by(preset_id=preset_id).delete()
            
            travellers_added = []
            for traveller in travellers:
                preset_traveller = PresetTraveller(preset_id=preset_id, user_id=traveller.user_id)
                db.session.add(preset_traveller)
                
                travellers_added.append({
                    "user_id": traveller.user_id,
                    "first_name": traveller.first_name,
                    "middle_name": traveller.middle_name,
                    "last_name": traveller.last_name,
                    "passport_number": traveller.passport_number
                })
            
            db.session.commit()

            response = {
                "preset_id": preset_id,
                "preset_name": preset_name,
                "created_by_user_id": user_id,
                "travellers_added": travellers_added
            }

            return api.marshal(response, preset_response_model), 200

        except Exception as e:
            db.session.rollback()
            return {"error_code": 400, "message": f"Error updating preset travellers: {str(e)}"}, 400

@ns_user.route('/<int:user_id>/update-vehicle')
@api.param('user_id', 'The user identifier')
class UpdateVehicleResource(Resource):
    @api.expect(vehicle_model)
    @api.response(200, 'Vehicle updated successfully', vehicle_model)
    @api.response(400, 'Invalid data format', error_response_model_400)
    @api.response(404, 'User ID not found', error_response_model_404)
    def put(self, user_id):
        data = request.get_json()

        user = UserSensitiveInformation.query.get(user_id)
        if not user:
            return {"error_code": 404, "message": "User not found"}, 404

        try:
            vehicle = Vehicle.query.filter_by(user_id=user_id).first()
            if not vehicle:
                return {"error_code": 404, "message": "Vehicle not found"}, 404

            if 'vehicle_number' in data and data['vehicle_number']:
                vehicle.vehicle_number = data['vehicle_number']

            if 'vehicle_make' in data and data['vehicle_make']:
                vehicle.vehicle_make = data['vehicle_make']

            if 'vehicle_model' in data and data['vehicle_model']:
                vehicle.vehicle_model = data['vehicle_model']

            if 'vehicle_color' in data and data['vehicle_color']:
                vehicle.vehicle_color = data['vehicle_color']

            db.session.commit()

            response_data = {
                "vehicle_number": vehicle.vehicle_number,
                "vehicle_make": vehicle.vehicle_make,
                "vehicle_model": vehicle.vehicle_model,
                "vehicle_color": vehicle.vehicle_color
            }

            return api.marshal(response_data, vehicle_model), 200

        except Exception as e:
            db.session.rollback()
            return {"error_code": 400, "message": f"Error updating vehicle: {str(e)}"}, 400

@ns_user.route('/<int:user_id>/update-traveller')
@api.param('user_id', 'The user identifier')
class UpdateTravellerResource(Resource):
    @api.expect(traveller_model)
    @api.response(200, 'Traveller updated successfully', traveller_model)
    @api.response(400, 'Invalid data format', error_response_model_400)
    @api.response(404, 'User ID not found', error_response_model_404)
    def put(self, user_id):
        data = request.get_json()

        user = UserSensitiveInformation.query.get(user_id)
        if not user:
            return {"error_code": 404, "message": "User not found"}, 404

        try:
            traveller = Traveller.query.filter_by(user_id=user_id).first()
            if not traveller:
                return {"error_code": 404, "message": "Traveller not found"}, 404

            if 'passport_number' in data and data['passport_number']:
                traveller.passport_number = data['passport_number']

            if 'first_name' in data and data['first_name']:
                traveller.first_name = data['first_name']

            if 'middle_name' in data and data['middle_name']:
                traveller.middle_name = data['middle_name']

            if 'last_name' in data and data['last_name']:
                traveller.last_name = data['last_name']

            if 'date_of_birth' in data and data['date_of_birth']:
                try:
                    traveller.date_of_birth = datetime.strptime(data['date_of_birth'], "%Y-%m-%d").date()
                except ValueError:
                    return {"error_code": 400, "message": "Invalid date format for date_of_birth. Use YYYY-MM-DD"}, 400

            if 'nationality' in data and data['nationality']:
                traveller.nationality = data['nationality']

            db.session.commit()

            response_data = {
                "passport_number": traveller.passport_number,
                "first_name": traveller.first_name,
                "middle_name": traveller.middle_name,
                "last_name": traveller.last_name,
                "date_of_birth": traveller.date_of_birth.strftime("%Y-%m-%d") if traveller.date_of_birth else None,
                "nationality": traveller.nationality
            }

            return api.marshal(response_data, traveller_model), 200

        except Exception as e:
            db.session.rollback()
            return {"error_code": 400, "message": f"Error updating traveller: {str(e)}"}, 400

if __name__ == '__main__':
    with app.app_context():
        db.drop_all()
        db.create_all() 
        insert_mock_data()  

    app.run(debug=True, host='0.0.0.0', port=5000)