from datetime import datetime
from app import db
from flask_restx import fields, Api

class UserSensitiveInformation(db.Model):
    __tablename__ = 'user_sensitive_information'
    user_id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    first_name = db.Column(db.String(50), nullable=False)
    middle_name = db.Column(db.String(50), nullable=True)
    last_name = db.Column(db.String(50), nullable=False)
    date_of_birth = db.Column(db.Date, nullable=False)
    passport_issuing_country = db.Column(db.String(255), nullable=False)
    passport_number = db.Column(db.String(20), nullable=False, unique=True)
    passport_expiry = db.Column(db.Date, nullable=False)

class Vehicle(db.Model):
    vehicle_id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    vehicle_number = db.Column(db.String(20), nullable=False, unique=True)

class UserVehicle(db.Model):
    user_vehicle_id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    user_id = db.Column(db.Integer, db.ForeignKey(UserSensitiveInformation.user_id), nullable=False)
    vehicle_id = db.Column(db.Integer, db.ForeignKey('vehicle.vehicle_id'), nullable=False)
    user_vehicle_model = db.Column(db.String(100), nullable=False)

class Pass(db.Model):
    pass_id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    creator_user_id = db.Column(db.Integer, db.ForeignKey(UserSensitiveInformation.user_id), nullable=False)
    pass_date = db.Column(db.DateTime, nullable=False)
    expiry_datetime = db.Column(db.DateTime, nullable=False) 
    pass_utilized = db.Column(db.Boolean, nullable=False, default=False)

class PassTraveller(db.Model):
    pass_traveller_id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    pass_id = db.Column(db.Integer, db.ForeignKey('pass.pass_id'), nullable=False)
    user_id = db.Column(db.Integer, db.ForeignKey(UserSensitiveInformation.user_id), nullable=False)

class Preset(db.Model):
    preset_id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    preset_name = db.Column(db.String(100), nullable=False)
    user_id = db.Column(db.Integer, db.ForeignKey(UserSensitiveInformation.user_id), nullable=False)

class PresetTraveller(db.Model):
    preset_traveller_id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    preset_id = db.Column(db.Integer, db.ForeignKey('preset.preset_id'), nullable=False)
    user_id = db.Column(db.Integer, db.ForeignKey(UserSensitiveInformation.user_id), nullable=False)

class UserTraveller(db.Model):
    user_traveller_id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    creator_user_id = db.Column(db.Integer, db.ForeignKey(UserSensitiveInformation.user_id), nullable=False)
    traveller_id = db.Column(db.Integer, db.ForeignKey(UserSensitiveInformation.user_id), nullable=False)

def create_models(api: Api):
    # Vehicle Models
    add_vehicle_model = api.model('AddVehicle', {
        'vehicle_number': fields.String(required=True, description="License plate number of the vehicle"),
        'user_vehicle_model': fields.String(required=True, description="Model of the vehicle user has entered")
    })

    add_vehicle_model_result = api.model('AddVehicleResult', {
        'user_vehicle': fields.Nested(api.model('UserVehicle', {
            'user_id': fields.Integer(readonly=True),
            'vehicle_id': fields.Integer(readonly=True),
            'vehicle_number': fields.String(required=True, description="Vehicle's license plate number"),
            'user_vehicle_model': fields.String(required=True, description="Model of the vehicle user has entered")
        }))
    })

    all_vehicles_model = api.model('AllUserVehicles', {
        'user_vehicle_id': fields.Integer(readonly=True),
        'user_vehicle_name': fields.String(required=True, description="Model name user has assigned to the vehicle"),
        'vehicle_id': fields.Integer(readonly=True),
        'vehicle_number': fields.String(required=True, description="Vehicle's license plate number")
    })

    # Preset Models
    preset_details_model = api.model('PresetDetailsWithUserId', {
        'user_id': fields.Integer(readonly=True, example=1, description="First name of the user"),
        'presets': fields.Nested(api.model('PresetDetails', {   
            'preset_id': fields.Integer(readonly=True),
            'preset_name': fields.String(required=True, description="The name of the preset"),
            'passenger_count': fields.Integer(required=True, description="The number of passengers in the preset")
        }))
    })

    # Traveller Models
    traveller_model_with_user_id = api.model('User', {
        'user_id': fields.Integer(required=True, example=1, description="Autogenerated id of the user"),
        'first_name': fields.String(required=True, example="Alice", description="First name of the user"),
        'middle_name': fields.String(example="J", description="Middle name of the user"),
        'last_name': fields.String(required=True, example="Smith", description="Last name of the user"),
        'passport_number': fields.String(required=True, example="A12345678", description="The passport number of the user")
    })

    traveller_model = api.model('Traveller', {
        'first_name': fields.String(required=True, description="First name of the traveller"),
        'middle_name': fields.String(description="Middle name of the traveller"),
        'last_name': fields.String(required=True, description="Last name of the traveller"),
        'passport_number': fields.String(required=True, description="Passport number of the traveller")
    })

    # Pass Models
    pass_response_model = api.model('PassResponseWithUserId', {
        'user_id': fields.Integer(required=True, example=1, description="Autogenerated id of the user"),
        "passes": fields.Nested(api.model('PassResponse', {
            'pass_id': fields.Integer(readonly=True),
            'pass_date': fields.String(required=True, description="Date when the pass was created (in String, NOT Datetime)"),
            'expiry_datetime': fields.String(required=True, description="Expiry date of the pass (in String, NOT Datetime)"),
            'pass_utilized': fields.Boolean(required=True, description="Whether the pass has been utilized for immigration"),
            'travellers': fields.List(fields.Nested(traveller_model_with_user_id), description="List of travellers associated with the pass")
        }))
    })

    # Error Models
    error_response_model_400 = api.model('ErrorResponse400', {
        'error_code': fields.Integer(example=400, description="Error code indicating the type of error"),
        'message': fields.String(example="Required fields missing or data already in database", description="Error message explaining the issue")
    })

    error_response_model_404 = api.model('ErrorResponse404', {
        'error_code': fields.Integer(example=404, description="Error code indicating the type of error"),
        'message': fields.String(example="Particular resource not found", description="Error message explaining the issue")
    })

    return {
        'add_vehicle_model': add_vehicle_model,
        'add_vehicle_model_result': add_vehicle_model_result,
        'all_vehicles_model': all_vehicles_model,
        'preset_details_model': preset_details_model,
        'traveller_model_with_user_id': traveller_model_with_user_id,
        'traveller_model': traveller_model,
        'pass_response_model': pass_response_model,
        'error_response_model_400': error_response_model_400,
        'error_response_model_404': error_response_model_404
    } 