from flask_restx import fields, Model

traveller_model = Model('Traveller', {
    'first_name': fields.String(required=True, description="First name of the traveller"),
    'middle_name': fields.String(description="Middle name of the traveller"),
    'last_name': fields.String(required=True, description="Last name of the traveller"),
    'passport_number': fields.String(required=True, description="Passport number of the traveller")
})

traveller_model_with_user_id = Model('TravellerWithUserId', {
    'user_id': fields.Integer(required=True, example=1, description="Autogenerated id of the user"),
    'first_name': fields.String(required=True, example="Alice", description="First name of the user"),
    'middle_name': fields.String(example="J", description="Middle name of the user"),
    'last_name': fields.String(required=True, example="Smith", description="Last name of the user"),
    'passport_number': fields.String(required=True, example="A12345678", description="The passport number of the user")
})

# Vehicle models
add_vehicle_model = Model('AddVehicle', {
    'vehicle_number': fields.String(required=True, description="License plate number of the vehicle"),
    'user_vehicle_model': fields.String(required=True, description="Model of the vehicle user has entered")
})

all_vehicles_model = Model('AllUserVehicles', {
    'user_vehicle_id': fields.Integer(readonly=True),
    'user_vehicle_name': fields.String(required=True, description="Model name user has assigned to the vehicle"),
    'vehicle_id': fields.Integer(readonly=True),
    'vehicle_number': fields.String(required=True, description="Vehicle's license plate number")
})

# Preset models
preset_details_model = Model('PresetDetailsWithUserId', {
    'user_id': fields.Integer(readonly=True, example=1, description="First name of the user"),
    'presets': fields.Nested(Model('PresetDetails', {   
        'preset_id': fields.Integer(readonly=True),
        'preset_name': fields.String(required=True, description="The name of the preset"),
        'passenger_count': fields.Integer(required=True, description="The number of passengers in the preset")
    }))
})

preset_with_users_model = Model('PresetWithUsers', {
    'preset_id': fields.Integer(readonly=True),
    'preset_name': fields.String(required=True, description="Name of the preset"),
    'users': fields.List(fields.Nested(traveller_model_with_user_id))
})

# Pass models
pass_response_model = Model('PassResponseWithUserId', {
    'user_id': fields.Integer(required=True, example=1, description="Autogenerated id of the user"),
    "passes": fields.Nested(Model('PassResponse', {
        'pass_id': fields.Integer(readonly=True),
        'pass_date': fields.String(required=True, description="Date when the pass was created (in String, NOT Datetime)"),
        'expiry_datetime': fields.String(required=True, description="Expiry date of the pass (in String, NOT Datetime)"),
        'pass_utilized': fields.Boolean(required=True, description="Whether the pass has been utilized for immigration"),
        'travellers': fields.List(fields.Nested(traveller_model_with_user_id), description="List of travellers associated with the pass")
    }))
})

create_pass_model = Model('CreatePass', {
    'creator_user_id': fields.Integer(required=True, description="User ID of the creator of the pass"),
    'pass_date': fields.String(required=True, description="Date and time of the pass creation (format: YYYY-MM-DD HH:MM:SS)"),
    'pass_utilized': fields.Boolean(required=True, description="Whether the pass is utilized or not"),
    'traveller_passport_numbers': fields.List(fields.String, required=True, description="List of traveller passport numbers")
})

# Error models
error_response_model_400 = Model('ErrorResponse400', {
    'error_code': fields.Integer(example=400, description="Error code indicating the type of error"),
    'message': fields.String(example="Required fields missing or data already in database", description="Error message explaining the issue")
})

error_response_model_404 = Model('ErrorResponse404', {
    'error_code': fields.Integer(example=404, description="Error code indicating the type of error"),
    'message': fields.String(example="Particular resource not found", description="Error message explaining the issue")
})

# Success models
success_message_model = Model('FieldUpdateSuccess', {
    'message': fields.String(
        required=True, 
        description="Field showing successful update of particular field", 
        example="The field you are trying to modify has been updated"
    )
}) 