from flask_restx import Resource, fields
from flask import request
from db_instance import db
from models import UserSensitiveInformation, Preset, PresetTraveller
from api_models import (
    preset_details_model,
    preset_response_model,
    error_response_model_400,
    error_response_model_404,
    success_message_model,
    preset_with_users_model,
    preset_with_users_model_2,
    retrieve_all_presets_for_user_model,
    delete_preset_model,
    update_preset_travellers_passport_model,
    traveller_model_with_user_id
)

def init_preset_routes(api):
    ns_preset = api.namespace('presets', description='Preset-related operations')

    @ns_preset.route('/<int:user_id>/preset-summary')
    class UserPresetsResource(Resource):
        @api.response(200, 'Success', preset_details_model)
        @api.response(404, 'Preset not found', error_response_model_404)
        def get(self, user_id):
            user = UserSensitiveInformation.query.get(user_id)
            if not user:
                return {"error": "User not found"}, 404

            presets = Preset.query.filter_by(user_id=user_id).all()

            presets_list = []
            for p in presets:
                passenger_count = db.session.query(PresetTraveller).filter_by(preset_id=p.preset_id).count()
                
                presets_list.append({
                    "preset_id": p.preset_id,
                    "preset_name": p.preset_name,
                    "passenger_count": passenger_count
                })

            response = {
                "user_id": user_id,
                "presets": presets_list
            }

            return api.marshal(response, preset_details_model), 200


    @ns_preset.route('/<int:user_id>/created-presets-with-users-additional')
    class UserCreatedPresetsWithUsersAdditionalResource(Resource):
        preset_with_users_and_count_model = api.model('PresetWithUsersAndCount', {
            'preset_id': fields.Integer(readonly=True),
            'preset_name': fields.String(required=True, description="Name of the preset"),
            'passenger_count': fields.Integer(required=True, description="Number of passengers in the preset"),
            'users': fields.List(fields.Nested(traveller_model_with_user_id))
        })

        retrieve_all_presets_with_count_model = api.model('AllPresetForUserWithCount', {
            'user_id': fields.Integer(required=True, example=1, description="Autogenerated id of the user"),
            'presets_created': fields.List(fields.Nested(preset_with_users_and_count_model))
        })

        @api.response(200, 'Success', retrieve_all_presets_with_count_model)
        @api.response(404, 'User not found', error_response_model_404)
        def get(self, user_id):
            user = UserSensitiveInformation.query.get(user_id)
            if not user:
                return {"error": "User not found"}, 404

            presets = (
                db.session.query(Preset.preset_id, Preset.preset_name)
                .filter(Preset.user_id == user_id)
                .all()
            )

            if not presets:
                return {"user_id": user_id, "presets_created": []}, 200

            presets_data = []
            for preset_id, preset_name in presets:
                preset_users = (
                    db.session.query(
                        UserSensitiveInformation.user_id,
                        UserSensitiveInformation.first_name,
                        UserSensitiveInformation.middle_name,
                        UserSensitiveInformation.last_name,
                        UserSensitiveInformation.passport_number
                    )
                    .join(PresetTraveller, UserSensitiveInformation.user_id == PresetTraveller.user_id)
                    .filter(PresetTraveller.preset_id == preset_id)
                    .all()
                )

                users_list = [
                    {
                        "user_id": u.user_id,
                        "first_name": u.first_name,
                        "middle_name": u.middle_name,
                        "last_name": u.last_name,
                        "passport_number": u.passport_number
                    }
                    for u in preset_users
                ]

                passenger_count = len(users_list)

                presets_data.append({
                    "preset_id": preset_id,
                    "preset_name": preset_name,
                    "passenger_count": passenger_count,
                    "users": users_list
                })

            response = {
                "user_id": user_id,
                "presets_created": presets_data
            }
            
            return api.marshal(response, self.retrieve_all_presets_with_count_model), 200



    @ns_preset.route('/<int:user_id>/created-presets-with-users')
    class UserCreatedPresetsWithUsersResource(Resource):
        @api.response(200, 'Success', retrieve_all_presets_for_user_model)
        @api.response(404, 'Preset not found', error_response_model_404)
        def get(self, user_id):
            user = UserSensitiveInformation.query.get(user_id)
            if not user:
                return {"error": "User not found"}, 404

            presets = (
                db.session.query(Preset.preset_id, Preset.preset_name)
                .filter(Preset.user_id == user_id)
                .all()
            )

            if not presets:
                return {"user_id": user_id, "presets_created": []}, 200

            presets_data = []
            for preset_id, preset_name in presets:
                preset_users = (
                    db.session.query(
                        UserSensitiveInformation.user_id,
                        UserSensitiveInformation.first_name,
                        UserSensitiveInformation.middle_name,
                        UserSensitiveInformation.last_name,
                        UserSensitiveInformation.passport_number
                    )
                    .join(PresetTraveller, UserSensitiveInformation.user_id == PresetTraveller.user_id)
                    .filter(PresetTraveller.preset_id == preset_id)
                    .all()
                )

                users_list = [
                    {
                        "user_id": u.user_id,
                        "first_name": u.first_name,
                        "middle_name": u.middle_name,
                        "last_name": u.last_name,
                        "passport_number": u.passport_number
                    }
                    for u in preset_users
                ]

                presets_data.append({
                    "preset_id": preset_id,
                    "preset_name": preset_name,
                    "users": users_list
                })

            response = {
                "user_id": user_id,
                "presets_created": presets_data
            }
            
            return api.marshal(response, retrieve_all_presets_for_user_model), 200


    @ns_preset.route('/<int:user_id>/delete-preset')
    class DeletePresetResource(Resource):
        @api.expect(delete_preset_model)
        @api.response(200, 'Preset deleted successfully', success_message_model)
        @api.response(400, 'Required fields missing', error_response_model_400)
        @api.response(404, 'User, preset not found, or preset does not belong to user', error_response_model_404)
        def delete(self, user_id):
            user = UserSensitiveInformation.query.get(user_id)
            if not user:
                return {"error_code": 404, "message": "User not found"}, 404

            data = request.get_json()
            preset_id = data.get("preset_id")

            if not preset_id:
                return {"error_code": 400, "message": "Preset ID is required"}, 400

            preset = Preset.query.get(preset_id)
            if not preset:
                return {"error_code": 404, "message": "Preset not found"}, 404

            if preset.user_id != user_id:
                return {
                    "error_code": 404, 
                    "message": "This preset does not belong to the specified user"
                }, 404

            try:
                PresetTraveller.query.filter_by(preset_id=preset_id).delete()
                
                db.session.delete(preset)
                db.session.commit()

                return {"message": f"Preset with ID {preset_id} has been deleted successfully"}, 200

            except Exception as e:
                db.session.rollback()
                return {"error_code": 400, "message": f"Error deleting preset: {str(e)}"}, 400


    @ns_preset.route('/create')
    class CreatePresetResource(Resource):
        @api.expect(preset_with_users_model_2)
        @api.response(200, 'Success', preset_response_model)
        @api.response(400, 'Preset name or User ID not given in input', error_response_model_400)
        @api.response(404, 'Creator User ID/Passport number of one of the travellers not found', error_response_model_404)
        def post(self):
            data = request.get_json()

            preset_name = data.get("preset_name")
            user_id = data.get("user_id")
            travellers = data.get("travellers", [])

            if not preset_name:
                return {"error": "Preset name is required"}, 400
            if not user_id:
                return {"error": "User ID is required"}, 400

            creator = UserSensitiveInformation.query.get(user_id)
            if not creator:
                return {"error": f"User with user ID {user_id} not found"}, 404

            new_preset = Preset(preset_name=preset_name, user_id=user_id)
            db.session.add(new_preset)
            db.session.commit()

            preset_id = new_preset.preset_id

            travellers_added = []

            for traveller in travellers:
                passport_number = traveller.get("passport_number")
                given_first_name = traveller.get("first_name")
                given_middle_name = traveller.get("middle_name")
                given_last_name = traveller.get("last_name")

                user_sensitive = UserSensitiveInformation.query.filter_by(passport_number=passport_number).first()
                if not user_sensitive:
                    return {"error": f"Traveller with passport number {passport_number} not found"}, 404

                traveller_user_id = user_sensitive.user_id

                preset_traveller = PresetTraveller(preset_id=preset_id, user_id=traveller_user_id)
                db.session.add(preset_traveller)

                travellers_added.append({
                    "user_id": traveller_user_id,
                    "first_name": given_first_name,
                    "middle_name": given_middle_name,
                    "last_name": given_last_name,
                    "passport_number": passport_number
                })

            db.session.commit()

            response = {
                "preset_id": preset_id,
                "preset_name": preset_name,
                "created_by_user_id": user_id,
                "travellers_added": travellers_added
            }

            return api.marshal(response, preset_response_model), 200
            
    @ns_preset.route('/<int:user_id>/update-preset-travellers-passport')
    class UpdatePresetTravellersPassportResource(Resource):
        @api.expect(update_preset_travellers_passport_model)
        @api.response(200, 'Preset travellers updated successfully', preset_response_model)
        @api.response(400, 'Required fields missing', error_response_model_400)
        @api.response(404, 'User, preset or traveller not found, or preset does not belong to user', error_response_model_404)
        def put(self, user_id):
            user = UserSensitiveInformation.query.get(user_id)
            if not user:
                return {"error_code": 404, "message": "User not found"}, 404

            data = request.get_json()
            preset_id = data.get("preset_id")
            preset_name = data.get("preset_name")
            passport_numbers = data.get("passport_numbers", [])

            if not preset_id:
                return {"error_code": 400, "message": "Preset ID is required"}, 400
            
            if not preset_name:
                return {"error_code": 400, "message": "Preset name is required"}, 400
            
            if not isinstance(passport_numbers, list):
                return {"error_code": 400, "message": "passport_numbers must be a list"}, 400

            preset = Preset.query.get(preset_id)
            if not preset:
                return {"error_code": 404, "message": "Preset not found"}, 404

            if preset.user_id != user_id:
                return {
                    "error_code": 404, 
                    "message": "This preset does not belong to the specified user"
                }, 404

            travellers = []
            for passport_number in passport_numbers:
                traveller = UserSensitiveInformation.query.filter_by(passport_number=passport_number).first()
                if not traveller:
                    return {
                        "error_code": 404, 
                        "message": f"Traveller with passport number {passport_number} not found"
                    }, 404
                travellers.append(traveller)

            try:
                preset.preset_name = preset_name

                PresetTraveller.query.filter_by(preset_id=preset_id).delete()
                
                travellers_added = []
                for traveller in travellers:
                    preset_traveller = PresetTraveller(preset_id=preset_id, user_id=traveller.user_id)
                    db.session.add(preset_traveller)
                    
                    travellers_added.append({
                        "user_id": traveller.user_id,
                        "first_name": traveller.first_name,
                        "middle_name": traveller.middle_name,
                        "last_name": traveller.last_name,
                        "passport_number": traveller.passport_number
                    })
                
                db.session.commit()

                response = {
                    "preset_id": preset_id,
                    "preset_name": preset_name,
                    "created_by_user_id": user_id,
                    "travellers_added": travellers_added
                }

                return api.marshal(response, preset_response_model), 200

            except Exception as e:
                db.session.rollback()
                return {"error_code": 400, "message": f"Error updating preset travellers: {str(e)}"}, 400

    return ns_preset

