from flask_restx import Namespace, Resource, fields
from app.services.pass_service import PassService
from app.api.models import create_models
from flask import request
from datetime import datetime, timedelta
from app import db
from app.models import UserSensitiveInformation, Pass, PassTraveller

ns_pass = Namespace('pass', description='Pass operations')
models = create_models(ns_pass)

# Create pass models
pass_response_model = ns_pass.model('PassResponseWithUserId', {
    'user_id': fields.Integer(required=True, example=1, description="Autogenerated id of the user"),
    "passes": fields.Nested(ns_pass.model('PassResponse', {
        'pass_id': fields.Integer(readonly=True),
        'pass_date': fields.String(required=True, description="Date when the pass was created (in String, NOT Datetime)"),
        'expiry_datetime': fields.String(required=True, description="Expiry date of the pass (in String, NOT Datetime)"),
        'pass_utilized': fields.Boolean(required=True, description="Whether the pass has been utilized for immigration"),
        'travellers': fields.List(fields.Nested(models['traveller_model_with_user_id']), description="List of travellers associated with the pass")
    }))
})

create_pass_model = ns_pass.model('CreatePass', {
    'creator_user_id': fields.Integer(required=True, description="User ID of the creator of the pass"),
    'pass_date': fields.String(required=True, description="Date and time of the pass creation (format: YYYY-MM-DD HH:MM:SS)"),
    'pass_utilized': fields.Boolean(required=True, description="Whether the pass is utilized or not"),
    'traveller_passport_numbers': fields.List(fields.String, required=True, description="List of traveller passport numbers")
})

pass_response_model_2 = ns_pass.model('PassResponse2', {
    'pass_id': fields.Integer(readonly=True),
    'creator_user_id': fields.Integer(required=True, description="User ID of the creator of the pass"),
    'pass_date': fields.String(required=True, description="Date and time of the pass creation"),
    'expiry_datetime': fields.String(required=True, description="Expiry date and time of the pass"),
    'pass_utilized': fields.Boolean(required=True, description="Whether the pass has been utilized"),
    'travellers_added': fields.List(fields.Nested(models['traveller_model_with_user_id']), description="List of travellers added to the pass")
})

pass_history_model = ns_pass.model('PassHistoryWithUserId', {
    'user_id': fields.Integer(required=True, example=1, description="Autogenerated id of the user"),
    "passes_utilized": fields.List(fields.Nested(ns_pass.model('PassHistory', {
        'pass_id': fields.Integer(readonly=True),
        'pass_date': fields.DateTime(required=True, description="Date when the pass was created"),
        'expiry_datetime': fields.DateTime(required=True, description="Expiry date and time of the pass")
    })))
})

pass_history_with_travellers_model = ns_pass.model('PassHistoryWithTravellers', {
    'user_id': fields.Integer(required=True, example=1, description="Autogenerated id of the user"),
    "passes_utilized": fields.List(fields.Nested(ns_pass.model('PassHistoryWithTravellersDetails', {
        'pass_id': fields.Integer(readonly=True),
        'pass_date': fields.DateTime(required=True, description="Date when the pass was created"),
        'expiry_datetime': fields.DateTime(required=True, description="Expiry date and time of the pass"),
        'travellers': fields.List(fields.Nested(models['traveller_model_with_user_id']), description="List of travellers associated with the pass")
    })))
})

pass_details_by_id_model = ns_pass.model('PassDetailsById', {
    'pass_id': fields.Integer(readonly=True, description="ID of the pass"),
    'pass_date': fields.String(required=True, description="Date and time of the pass"),
    'expiry_datetime': fields.String(required=True, description="Expiry date and time of the pass"),
    'pass_utilized': fields.Boolean(required=True, description="Whether the pass has been utilized"),
    'passenger_count': fields.Integer(required=True, description="Number of passengers in the pass"),
    'travellers': fields.List(fields.Nested(models['traveller_model_with_user_id']), description="List of travellers in the pass")
})

pass_details_request_model = ns_pass.model('PassDetailsRequest', {
    'pass_id': fields.Integer(required=True, description="ID of the pass to retrieve details for", example=1)
})

pass_details_by_user_model = ns_pass.model('PassDetailsByUser', {
    'user_id': fields.Integer(readonly=True, description="ID of the user"),
    'passes': fields.List(fields.Nested(ns_pass.model('PassDetails', {
        'pass_id': fields.Integer(readonly=True, description="ID of the pass"),
        'pass_date': fields.String(required=True, description="Date and time of the pass"),
        'expiry_datetime': fields.String(required=True, description="Expiry date and time of the pass"),
        'pass_utilized': fields.Boolean(required=True, description="Whether the pass has been utilized"),
        'passenger_count': fields.Integer(required=True, description="Number of passengers in the pass"),
        'travellers': fields.List(fields.Nested(models['traveller_model_with_user_id']), description="List of travellers in the pass")
    })))
})

@ns_pass.route('/<int:user_id>/passes')
class UserPassesResource(Resource):
    @ns_pass.response(200, 'Success', pass_response_model)
    @ns_pass.response(404, 'User ID not found', models['error_response_model_404'])
    def get(self, user_id):
        user = UserSensitiveInformation.query.get(user_id)
        if not user:
            return {"error": "User not found"}, 404

        passes = (
            db.session.query(
                Pass.pass_id,
                Pass.pass_date,
                Pass.expiry_datetime,
                Pass.pass_utilized
            )
            .filter(Pass.creator_user_id == user_id)
            .all()
        )

        passes_list = []
        for p in passes:
            travellers = (
                db.session.query(
                    UserSensitiveInformation.user_id,
                    UserSensitiveInformation.first_name,
                    UserSensitiveInformation.middle_name,
                    UserSensitiveInformation.last_name,
                    UserSensitiveInformation.passport_number
                )
                .join(PassTraveller, UserSensitiveInformation.user_id == PassTraveller.user_id)
                .filter(PassTraveller.pass_id == p.pass_id)
                .all()
            )

            travellers_list = [
                {
                    "user_id": t.user_id,
                    "first_name": t.first_name,
                    "middle_name": t.middle_name,
                    "last_name": t.last_name,
                    "passport_number": t.passport_number
                }
                for t in travellers
            ]

            passes_list.append({
                "pass_id": p.pass_id,
                "expiry_datetime": p.expiry_datetime.strftime("%Y-%m-%d %H:%M:%S"),
                "pass_date": p.pass_date.strftime("%Y-%m-%d %H:%M:%S"),
                "pass_utilized": p.pass_utilized,
                "travellers": travellers_list
            })

        response = {
            "user_id": user_id,
            "passes": passes_list
        }

        return ns_pass.marshal(response, pass_response_model), 200

@ns_pass.route('/create')
class CreatePassResource(Resource):
    @ns_pass.expect(create_pass_model)
    @ns_pass.response(200, 'Success', pass_response_model_2)
    @ns_pass.response(400, 'Missing required fields like Pass user id and pass date or invalid date format ', models['error_response_model_400'])
    @ns_pass.response(404, 'Resource not found', models['error_response_model_404'])
    def post(self):
        data = request.get_json()

        creator_user_id = data.get("creator_user_id")
        pass_date = data.get("pass_date")
        pass_utilized = data.get("pass_utilized", False)
        traveller_passport_numbers = data.get("traveller_passport_numbers", [])

        if not all([creator_user_id, pass_date]):
            return {"error": "Missing required fields - Pass user id and pass date"}, 400

        try:
            pass_date = datetime.strptime(pass_date, "%Y-%m-%d %H:%M:%S").date()
            expiry_datetime = pass_date + timedelta(hours=24)
    
        except ValueError:
            return {"error": "Invalid date format"}, 400

        new_pass = Pass(
            creator_user_id=creator_user_id,
            expiry_datetime=expiry_datetime,
            pass_date=pass_date,
            pass_utilized=pass_utilized,
        )

        db.session.add(new_pass)
        db.session.commit()

        pass_id = new_pass.pass_id

        travellers_added = []

        for passport_number in traveller_passport_numbers:
            user_sensitive = UserSensitiveInformation.query.filter_by(passport_number=passport_number).first()
            if not user_sensitive:
                return {"error": f"Traveller with passport number {passport_number} not found"}, 404

            traveller_user_id = user_sensitive.user_id

            pass_traveller = PassTraveller(pass_id=pass_id, user_id=traveller_user_id)
            db.session.add(pass_traveller)

            travellers_added.append({
                "user_id": traveller_user_id,
                "first_name": user_sensitive.first_name,
                "middle_name": user_sensitive.middle_name,
                "last_name": user_sensitive.last_name,
                "passport_number": passport_number
            })

        db.session.commit()

        response = {
            "pass_id": pass_id,
            "creator_user_id": creator_user_id,
            "pass_date": pass_date.strftime("%Y-%m-%d %H:%M:%S"),
            "expiry_datetime": expiry_datetime.strftime("%Y-%m-%d %H:%M:%S"),
            "pass_utilized": pass_utilized,
            "travellers_added": travellers_added
        }

        return ns_pass.marshal(response, pass_response_model_2), 200

@ns_pass.route('/<int:user_id>/passes-history-all')
class UserPassHistoryWithTravellersResource(Resource):
    @ns_pass.response(200, 'Success', pass_history_with_travellers_model)
    @ns_pass.response(404, 'Resource not found', models['error_response_model_404'])
    def get(self, user_id):
        user = UserSensitiveInformation.query.get(user_id)
        if not user:
            return {"error_code": 404, "message": "User not found"}, 404

        utilized_passes = (
            db.session.query(
                Pass.pass_id,
                Pass.pass_date,
                Pass.expiry_datetime
            )
            .filter(Pass.creator_user_id == user_id, Pass.pass_utilized == True)
            .all()
        )

        passes_list = []
        for p in utilized_passes:
            travellers = (
                db.session.query(
                    UserSensitiveInformation.user_id,
                    UserSensitiveInformation.first_name,
                    UserSensitiveInformation.middle_name,
                    UserSensitiveInformation.last_name,
                    UserSensitiveInformation.passport_number
                )
                .join(PassTraveller, UserSensitiveInformation.user_id == PassTraveller.user_id)
                .filter(PassTraveller.pass_id == p.pass_id)
                .all()
            )
            travellers_list = [
                {
                    "user_id": t.user_id,
                    "first_name": t.first_name,
                    "middle_name": t.middle_name,
                    "last_name": t.last_name,
                    "passport_number": t.passport_number
                }
                for t in travellers
            ]
            passes_list.append({
                "pass_id": p.pass_id,
                "pass_date": p.pass_date,
                "expiry_datetime": p.expiry_datetime,
                "travellers": travellers_list
            })

            response = {
                "user_id": user_id,
                "passes_utilized": passes_list
            }
        return ns_pass.marshal(response, pass_history_with_travellers_model), 200

@ns_pass.route('/details')
class PassDetailsByIdResource(Resource):
    @ns_pass.expect(pass_details_request_model)
    @ns_pass.response(200, 'Success', pass_details_by_id_model)
    @ns_pass.response(400, 'Missing pass ID', models['error_response_model_400'])
    @ns_pass.response(404, 'Pass not found', models['error_response_model_404'])
    def post(self):
        data = request.get_json()
        pass_id = data.get("pass_id")
        if not pass_id:
            return {"error_code": 400, "message": "Pass ID is required"}, 400
        pass_entry = Pass.query.get(pass_id)
        if not pass_entry:
            return {"error_code": 404, "message": "Pass not found"}, 404
        travellers = (
            db.session.query(
                UserSensitiveInformation.user_id,
                UserSensitiveInformation.first_name,
                UserSensitiveInformation.middle_name,
                UserSensitiveInformation.last_name,
                UserSensitiveInformation.passport_number
            )
            .join(PassTraveller, UserSensitiveInformation.user_id == PassTraveller.user_id)
            .filter(PassTraveller.pass_id == pass_id)
            .all()
        )
        travellers_list = [
            {
                "user_id": t.user_id,
                "first_name": t.first_name,
                "middle_name": t.middle_name,
                "last_name": t.last_name,
                "passport_number": t.passport_number
            }
            for t in travellers
        ]
        passenger_count = len(travellers_list)
        response = {
            "pass_id": pass_id,
            "pass_date": pass_entry.pass_date.strftime("%Y-%m-%d %H:%M:%S"),
            "expiry_datetime": pass_entry.expiry_datetime.strftime("%Y-%m-%d %H:%M:%S"),
            "pass_utilized": pass_entry.pass_utilized,
            "passenger_count": passenger_count,
            "travellers": travellers_list
        }

        return ns_pass.marshal(response, pass_details_by_id_model), 200

@ns_pass.route('/<int:user_id>/details')
class UserPassDetailsResource(Resource):
    @ns_pass.response(200, 'Success', pass_details_by_user_model)
    @ns_pass.response(404, 'User not found', models['error_response_model_404'])
    def get(self, user_id):
        user = UserSensitiveInformation.query.get(user_id)
        if not user:
            return {"error_code": 404, "message": "User not found"}, 404
        pass_id = request.args.get('pass_id', None)
        passes_query = Pass.query.filter(Pass.creator_user_id == user_id)
        if pass_id is not None:
            try:
                pass_id = int(pass_id)
                passes_query = passes_query.filter(Pass.pass_id == pass_id)
            except ValueError:
                return {"error_code": 400, "message": "Invalid pass_id parameter"}, 400
        
        passes = passes_query.all()
        passes_list = []
        for pass_entry in passes:
            travellers = (
                db.session.query(
                    UserSensitiveInformation.user_id,
                    UserSensitiveInformation.first_name,
                    UserSensitiveInformation.middle_name,
                    UserSensitiveInformation.last_name,
                    UserSensitiveInformation.passport_number
                )
                .join(PassTraveller, UserSensitiveInformation.user_id == PassTraveller.user_id)
                .filter(PassTraveller.pass_id == pass_entry.pass_id)
                .all()
            )
            travellers_list = [
                {
                    "user_id": t.user_id,
                    "first_name": t.first_name,
                    "middle_name": t.middle_name,
                    "last_name": t.last_name,
                    "passport_number": t.passport_number
                }
                for t in travellers
            ]
            passenger_count = len(travellers_list)
            passes_list.append({
                "pass_id": pass_entry.pass_id,
                "pass_date": pass_entry.pass_date.strftime("%Y-%m-%d %H:%M:%S"),
                "expiry_datetime": pass_entry.expiry_datetime.strftime("%Y-%m-%d %H:%M:%S"),
                "pass_utilized": pass_entry.pass_utilized,
                "passenger_count": passenger_count,
                "travellers": travellers_list
            })
        response = {
            "user_id": user_id,
            "passes": passes_list
        }

        return ns_pass.marshal(response, pass_details_by_user_model), 200 